+++
name = "Books"
description = "Books I want to read or have read."
uuid = "books-to-read"
tags = ["project", "index-page"]
+++

* 1421: The Year China Discovered America
** Gavin Menzies
** Rating: 3.58 / 11201
** Description
On 3/8/1421, the largest fleet the world had ever seen set sail from China. Its mission was "to proceed all the way to the ends of the earth to collect tribute from the barbarians beyond the seas" &amp; unite the whole world in Confucian harmony. When it returned in 10/1423, the emperor had fallen, leaving China in political &amp; economic chaos. The great ships were left to rot at their moorings. Most records of their journeys were destroyed. Lost in China's long, self-imposed isolation that fo

* A Brief History of Time
** Stephen Hawking
** Rating: 4.13 / 190369
** Description
In the ten years since its publication in 1988, Stephen Hawking's classic work has become a landmark volume in scientific writing, with more than nine million copies in forty languages sold worldwide. That edition was on the cutting edge of what was then known about the origins and nature of the universe. But the intervening years have seen extraordinary advances in the technology of observing both the micro- and the macrocosmic worlds. These observations have confirmed many of Professor Hawking

* A Game of Thrones (A Song of Ice and Fire, #1)
** George R.R. Martin
** Rating: 4.45 / 1491045
** Description
Summers span decades. Winter can last a lifetime. And the struggle for the Iron Throne has begun.  As Warden of the north, Lord Eddard Stark counts it a curse when King Robert bestows on him the office of the Hand. His honour weighs him down at court where a true man does what he will, not what he must … and a dead enemy is a thing of beauty.  The old gods have no power in the south, Stark’s family is split and there is treachery at court. Worse, the vengeance-mad heir of the

* A Heartbreaking Work of Staggering Genius
** Dave Eggers
** Rating: 3.68 / 151499
** Description
'When you read his extraordinary memoir you don't laugh, then cry, then laugh again; you somehow experience these emotions all at once.'  "Well, this was when Bill was sighing a lot. He had decided that after our parents died he just didn't want any more fighting between what was left of us. He was twenty-four, Beth was twenty-three, I was twenty-one, Toph was eight, and all of us were so tried already, from that winter. So when something would come up, any little thing, some bill to p

* A Long Way Gone: Memoirs of a Boy Soldier
** Ishmael Beah
** Rating: 4.14 / 126582
** Description
The devastating story of war through the eyes of a child soldier. Beah tells how, at the age of twelve, he fled attacking rebels and wandered a land rendered unrecognizable by violence. By thirteen, he’d been picked up by the government army, and became a soldier.  My new friends have begun to suspect I haven’t told them the full story of my life. “Why did you leave Sierra Leone?” “Because there is a war.” “You mean, you saw people running around with guns and shooting e

* A People's History of the United States
** Howard Zinn
** Rating: 4.07 / 148551
** Description
Known for its lively, clear prose as well as its scholarly research, A People's History of the United States is the only volume to tell America's story from the point of view of—and in the words of—America's women, factory workers, African Americans, Native Americans, working poor, and immigrant laborers.

* A Prayer for Owen Meany
** John Irving
** Rating: 4.22 / 249806
** Description
Eleven-year-old Owen Meany, playing in a Little League baseball game in Gravesend, New Hampshire, hits a foul ball and kills his best friend's mother. Owen doesn't believe in accidents; he believes he is God's instrument. What happens to Owen after that 1953 foul is both extraordinary and terrifying. At moments a comic, self-deluded victim, but in the end the principal, tragic actor in a divine plan, Owen Meany is the most heartbreaking hero John Irving has yet created.  ~from back cov

* A Random Walk Down Wall Street
** Burton G. Malkiel
** Rating: 4.06 / 15688
** Description
Using the dot-com crash as an object lesson in how not to manage your portfolio, here is the best-selling, gimmick-free, irreverent, vastly informative guide to navigating the turbulence of the market and managing investments with confidence.  A Random Walk Down Wall Street is well established as a staple of the business shelf, the first book any investor should read before taking the plunge and starting a portfolio. With its life-cycle guide to investing, it matches the needs

* A Streetcar Named Desire
** Tennessee Williams
** Rating: 3.97 / 216068
** Description
The Pulitzer Prize and Drama Critics Circle Award winning play—reissued with an introduction by Arthur Miller (Death of a Salesman and The Crucible), and Williams’ essay “The World I Live In.”  It is a very short list of 20th-century American plays that continue to have the same power and impact as when they first appeared—57 years after its Broadway premiere, Tennessee Williams’ A Streetcar Named Desire is one of those plays. The story famously recounts how the fa

* A Treatise of Human Nature
** David Hume
** Rating: 3.91 / 9223
** Description
A Treatise of Human Nature (1739-40), David Hume's comprehensive attempt to base philosophy on a new, observationally grounded study of human nature, is one of the most important texts in Western philosophy. It is also the focal point of current attempts to understand 18th-century philosophy. The Treatise first explains how we form such concepts as cause and effect, external existence, and personal identity, and to form compelling but unconfirmable beliefs in the entities represented by these co

* A Whole New Mind: Why Right-Brainers Will Rule the Future
** Daniel H. Pink
** Rating: 3.95 / 22479
** Description


* A Wrinkle in Time (A Wrinkle in Time Quintet, #1)
** Madeleine L'Engle
** Rating: 4.04 / 670689
** Description
It was a dark and stormy night; Meg Murry, her small brother Charles Wallace, and her mother had come down to the kitchen for a midnight snack when they were upset by the arrival of a most disturbing stranger.   "Wild nights are my glory," the unearthly stranger told them. "I just got caught in a downdraft and blown off course. Let me be on my way. Speaking of way, by the way, there is such a thing as a tesseract".  Meg's father had been experimenting with this fifth dimensio

* Accounting Made Simple: Accounting Explained in 100 Pages or Less
** Mike Piper
** Rating: 3.86 / 3682
** Description
Find all of the following explained in Plain-English with no technical jargon: The Accounting Equation and why it's so significant How to read and prepare financial statements How to calculate and interpret several different financial ratios The concepts and assumptions behind Generally Accepted Accounting Principles (GAAP) Preparing journal entries with debits and credits Cash method vs. accrual method Inventory and Cost of Goods Sold How to calculate depreciation and amortization expenses

* Against the Gods: The Remarkable Story of Risk
** Peter L. Bernstein
** Rating: 3.96 / 8688
** Description
With the stock market breaking records almost daily, leaving longtime market analysts shaking their heads and revising their forecasts, a study of the concept of risk seems quite timely. Peter Bernstein has written a comprehensive history of man's efforts to understand risk and probability, beginning with early gamblers in ancient Greece, continuing through the 17th-century French mathematicians Pascal and Fermat and up to modern chaos theory. Along the way he demonstrates that understanding ris

* Agile Estimating and Planning
** Mike Cohn
** Rating: 4.08 / 1566
** Description
Praise for Agile Estimating and Planning "Traditional, deterministic approaches to planning and estimating simply don't cut it on the slippery slopes of today's dynamic, change-driven projects. Mike Cohn's breakthrough book gives us not only the philosophy, but also the guidelines and a proven set of tools that we need to succeed in planning, estimating, and scheduling projects with a high uncertainty factor. At the same time, the author never loses sight of the need to deliver business v

* Agile Product Management with Scrum: Creating Products That Customers Love
** Roman Pichler
** Rating: 3.81 / 865
** Description
The First Guide to Scrum-Based Agile Product Management In   Agile Product Management with Scrum,   leading Scrum consultant Roman Pichler uses real-world examples to demonstrate how product owners can create successful products with Scrum. He describes a broad range of agile product management practices, including making agile product discovery work, taking advantage of emergent requirements, creating the minimal marketable product, leveraging early customer feedback

* Agile Project Management with Scrum
** Ken Schwaber
** Rating: 3.66 / 1166
** Description
The rules and practices for Scrum—a simple process for managing complex projects—are few, straightforward, and easy to learn. But Scrum’s simplicity itself—its lack of prescription—can be disarming, and new practitioners often find themselves reverting to old project management habits and tools and yielding lesser results. In this illuminating series of case studies, Scrum co-creator and evangelist Ken Schwaber identifies the real-world lessons—the successes and failures—culled from his years of

* Alice in Wonderland
** Jane Carruth
** Rating: 4.03 / 346728
** Description

  This is an adaptation. For the editions of the original book, see here
.  Alice's Adventures in Wonderland (commonly shortened to Alice in Wonderland) is an 1865 novel written by English mathematician Charles Lutwidge Dodgson under the pseudonym Lewis Carroll. It tells of a girl named Alice falling through a rabbit hole into a fantasy world populated by p

* All Quiet on the Western Front
** Erich Maria Remarque
** Rating: 3.93 / 273817
** Description
This is the testament of Paul Bäumer, who enlists with his classmates in the German army of World War I. These young men become enthusiastic soldiers, but their world of duty, culture, and progress breaks into pieces under the first bombardment in the trenches.   Through years of vivid horror, Paul holds fast to a single vow: to fight against the hatred that meaninglessly pits young men of the same generation but different uniforms against one another – if only he can come out of the w

* All the President's Men
** Carl Bernstein
** Rating: 4.17 / 35759
** Description
This landmark book details all the events of the biggest political scandal in the history of this nation--Watergate. Woodward and Bernstein kept the headlines coming, delivering revelation after amazing revelation to a shocked public. Black-and-white photograph section.

* Amusing Ourselves to Death: Public Discourse in the Age of Show Business
** Neil Postman
** Rating: 4.15 / 11639
** Description
Television has conditioned us to tolerate visually entertaining material measured out in spoonfuls of time, to the detriment of rational public discourse and reasoned public affairs. In this eloquent, persuasive book, Neil Postman alerts us to the real and present dangers of this state of affairs, and offers compelling suggestions as to how to withstand the media onslaught. Before we hand over politics, education, religion, and journalism to the show business demands of the television age, we mu

* An American Tragedy
** Theodore Dreiser
** Rating: 3.94 / 27439
** Description
On one level, An American Tragedy is the story of the corruption and destruction of one man, Clyde Griffiths, who forfeits his life in desperate pursuit of success. On a deeper, more profound level, the novel represents a massive portrayal of the society whose values both shape Clyde's tawdry ambitions and seal his fate: It is an unsurpassed depiction of the harsh realities of American life and of the dark side of the American Dream. Extraordinary in scope and power, vivid in its sense of

* An Enquiry Concerning Human Understanding
** David Hume
** Rating: 3.91 / 13482
** Description
Philosopher David Hume was considered to one of the most important figures in the age of Scottish enlightenment. In "An Enquiry Concerning Human Understanding" Hume discusses the weakness that humans have in their abilities to comprehend the world around them, what is referred to in the title as human understanding. This work, now commonly required reading in philosophy classes, exposed a broad audience to philosophy when it was first published. A great introduction to the philosophy of David Hu

* Anansi Boys
** Neil Gaiman
** Rating: 4.01 / 156960
** Description
God is dead. Meet the kids.  Fat Charlie Nancy's normal life ended the moment his father dropped dead on a Florida karaoke stage. Charlie didn't know his dad was a god. And he never knew he had a brother.   Now brother Spider's on his doorstep -- about to make Fat Charlie's life more interesting... and a lot more dangerous.

* And Then There Were None
** Agatha Christie
** Rating: 4.23 / 482834
** Description
First, there were ten - a curious assortment of strangers summoned as weekend guests to a private island off the coast of Devon. Their host, an eccentric millionaire unknown to all of them, is nowhere to be found. All that the guests have in common is a wicked past they're unwilling to reveal - and a secret that will seal their fate. For each has been marked for murder. One by one they fall prey. Before the weekend is out, there will be none. And only the dead are above suspicion.

* Angela's Ashes (Frank McCourt, #1)
** Frank McCourt
** Rating: 4.08 / 429723
** Description
Imbued on every page with Frank McCourt's astounding humor and compassion. This is a glorious book that bears all the marks of a classic.  "When I look back on my childhood I wonder how I managed to survive at all. It was, of course, a miserable childhood: the happy childhood is hardly worth your while. Worse than the ordinary miserable childhood is the miserable Irish childhood, and worse yet is the miserable Irish Catholic childhood."   So begins the Pulitzer Prize winning

* Apprenticeship Patterns: Guidance for the Aspiring Software Craftsman
** Dave Hoover
** Rating: 4.08 / 614
** Description
Are you doing all you can to further your career as a software developer? With today's rapidly changing and ever-expanding technologies, being successful requires more than technical expertise. To grow professionally, you also need soft skills and effective learning techniques. Honing those skills is what this book is all about. Authors Dave Hoover and Adewale Oshineye have cataloged dozens of behavior patterns to help you perfect essential aspects of your craft.   Compiled from years

* Are You There God? It's Me, Margaret
** Judy Blume
** Rating: 3.89 / 164176
** Description
Margaret Simon, almost twelve, likes long hair, tuna fish, the smell of rain, and things that are pink. She’s just moved from New York City to Farbook, New Jersey, and is anxious to fit in with her new friends—Nancy, Gretchen, and Janie. When they form a secret club to talk about private subjects like boys, bras, and getting their first periods, Margaret is happy to belong.  But none of them can believe Margaret doesn’t have religion, and that she isn’t going to the Y or the Jewish Com

* As I Lay Dying
** William Faulkner
** Rating: 3.72 / 112789
** Description
As I Lay Dying is Faulkner's harrowing account of the Bundren family's odyssey across the Mississippi countryside to bury Addie, their wife and mother. Told in turns by each of the family members—including Addie herself—the novel ranges in mood from dark comedy to the deepest pathos.

* Bel Canto
** Ann Patchett
** Rating: 3.92 / 203764
** Description
In an unnamed South American country, a world-renowned soprano sings at a birthday party in honor of a visiting Japanese industrial titan. Alas, in the opening sequence, a ragtag band of 18 terrorists enters the vice-presidential mansion through the air conditioning ducts. Their quarry is the president, who has unfortunately stayed home to watch a favorite soap opera. And thus, from the beginning, things go awry.  Among the hostages are Russian, Italian, and French diplomatic types. Sw

* Beloved
** Toni Morrison
** Rating: 3.77 / 249916
** Description
Staring unflinchingly into the abyss of slavery, this spellbinding novel transforms history into a story as powerful as Exodus and as intimate as a lullaby.   Sethe was born a slave and escaped to Ohio, but eighteen years later she is still not free. She has too many memories of Sweet Home, the beautiful farm where so many hideous things happened. Her new home is haunted by the ghost of her baby, who died nameless and whose tombstone is engraved with a single word: Beloved.  From Nobel Prize–winning author José Saramago, a magnificent, mesmerizing parable of loss  A city is hit by an epidemic of "white blindness" that spares no one. Authorities confine the blind to an empty mental hospital, but there the criminal element holds everyone captive, stealing food rations and assaulting women. There is one eyewitness to this nightmare who guides her charges—among them a boy with no mother, a girl with dark glasses, a dog of tears—through the barren street

* Blood Meridian, or the Evening Redness in the West
** Cormac McCarthy
** Rating: 4.18 / 81721
** Description
An epic novel of the violence and depravity that attended America's westward expansion, Blood Meridian brilliantly subverts the conventions of the Western novel and the mythology of the "wild west." Based on historical events that took place on the Texas-Mexico border in the 1850s, it traces the fortunes of the Kid, a fourteen-year-old Tennesseean who stumbles into the nightmarish world where Indians are being murdered and the market for their scalps is thriving.  Publisher's

* Book of Five Rings
** Miyamoto Musashi
** Rating: 4.09 / 25571
** Description
Miyamoto Musashi fue el más célebre de los guerreros (samurais) japoneses. En este texto presenta su modelo filosófico de vida a caballo entre el Zen y la religión Shinto, enlazándolo con todo un conjunto de técnicas de espada (kendo). Edición ilustrada.

* Born to Run: A Hidden Tribe, Superathletes, and the Greatest Race the World Has Never Seen
** Christopher McDougall
** Rating: 4.27 / 124766
** Description
Full of incredible characters, amazing athletic achievements, cutting-edge science, and, most of all, pure inspiration, Born to Run is an epic adventure that began with one simple question: Why does my foot hurt? In search of an answer, Christopher McDougall sets off to find a tribe of the world’s greatest distance runners and learn their secrets, and in the process shows us that everything we thought we knew about running is wrong.  Isolated by the most savage terrain in

* Brain Rules: 12 Principles for Surviving and Thriving at Work, Home, and School
** John Medina
** Rating: 4.00 / 22525
** Description
Most of us have no idea what’s really going on inside our heads. Yet brain scientists have uncovered details every business leader, parent, and teacher should know—like the need for physical activity to get your brain working its best.  How do we learn? What exactly do sleep and stress do to our brains? Why is multi-tasking a myth? Why is it so easy to forget—and so important to repeat new knowledge? Is it true that men and women have different brains?  In Brain Rules,

* Breakfast of Champions
** Kurt Vonnegut Jr.
** Rating: 4.08 / 189918
** Description
In Breakfast of Champions, one of Kurt Vonnegut’s  most beloved characters, the aging writer Kilgore Trout, finds to his horror that a Midwest car dealer is taking his fiction as truth. What follows is murderously funny satire, as Vonnegut looks at war, sex, racism, success, politics, and pollution in America and reminds us how to see the truth.

* Breath, Eyes, Memory
** Edwidge Danticat
** Rating: 3.86 / 23233
** Description
At an astonishingly young age, Edwidge Danticat has become one of our most celebrated new novelists, a writer who evokes the wonder, terror, and heartache of her native Haiti--and the enduring strength of Haiti's women--with a vibrant imagery and narrative grace that bear witness to her people's suffering and courage.    At the age of twelve, Sophie Caco is sent from her impoverished village of Croix-des-Rosets to New York, to be reunited with a mother she barely remembers. There she d

* Built to Last: Successful Habits of Visionary Companies
** James C. Collins
** Rating: 3.98 / 42590
** Description
"This is not a book about charismatic visionary leaders. It is not about visionary product concepts or visionary products or visionary market insights. Nor is it about just having a corporate vision. This is a book about something far more important, enduring, and substantial. This is a book about visionary companies." So write Jim Collins and Jerry Porras in this groundbreaking book that shatters myths, provides new insights, and gives practical guidance to those who would like to build landmar

* Cannery Row
** John Steinbeck
** Rating: 4.02 / 90860
** Description
Cannery Row is a book without much of a plot. Rather, it is an attempt to capture the feeling and people of a place, the cannery district of Monterey, California, which is populated by a mix of those down on their luck and those who choose for other reasons not to live "up the hill" in the more respectable area of town. The flow of the main plot is frequently interrupted by short vignettes that introduce us to various denizens of the Row, most of whom are not directly connected with the c

* Capital, Vol 1: A Critical Analysis of Capitalist Production
** Karl Marx
** Rating: 4.19 / 5796
** Description
Capital, one of Marx's major and most influential works, was the product of thirty years close study of the capitalist mode of production in England, the most advanced industrial society of his day. This new translation of Volume One, the only volume to be completed and edited by Marx himself, avoids some of the mistakes that have marred earlier versions and seeks to do justice to the literary qualities of the work. The introduction is by Ernest Mandel, author of Late Capitalism

* Cat's Cradle
** Kurt Vonnegut Jr.
** Rating: 4.17 / 279395
** Description
Told with deadpan humour &amp; bitter irony, Kurt Vonnegut's cult tale of global destruction preys on our deepest fears of witnessing Armageddon &amp;, worse still, surviving it ...  Dr Felix Hoenikker, one of the founding 'fathers' of the atomic bomb, has left a deadly legacy to the world. For he's the inventor of 'ice-nine', a lethal chemical capable of freezing the entire planet. The search for its whereabouts leads to Hoenikker's three ecentric children, to a crazed dictator

* Cesar Birotteau
** Honoré de Balzac
** Rating: 3.68 / 658
** Description
Honore de Balzac lived most of his life one step from his creditors; his house in Paris even had a special exit for avoiding them. No one knew more about money problems than Balzac, &amp; this is his subject in Rise and Fall of Cesar Birotteau--one of Balzac's greatest novels.   It's the story of Cesar Birotteau, an honest perfumer who's lured into overextending himself. This luring is the work of the unsavory du Tillet, an employee Birotteau fired for embezzlement. The Embezzler wor

* Charlie and the Chocolate Factory (Charlie Bucket, #1)
** Roald Dahl
** Rating: 4.11 / 505373
** Description
Complete with stunning new movie art for the cover, and an eight-page full-color insert of stills from director Tim Burton's new adaptation, Dahl's treasured novel appears unabridged in this tie-in edition.

* Charlotte's Web
** E.B. White
** Rating: 4.15 / 1119394
** Description
This beloved book by E. B. White, author of Stuart Little and The Trumpet of the Swan, is a classic of children's literature that is "just about perfect." Some Pig. Humble. Radiant. These are the words in Charlotte's Web, high up in Zuckerman's barn. Charlotte's spiderweb tells of her feelings for a little pig named Wilbur, who simply wants a friend. They also express the love of a girl named Fern, who saved Wilbur's life when he was born the runt of his litter. E. B. White's Newbery H

* Chinese: A Comprehensive Grammar
** Yip Po-Ching
** Rating: 4.22 / 9
** Description


* Chinese: A Comprehensive Grammar
** Yip Po-Ching
** Rating: 4.22 / 9
** Description


* Clean Code: A Handbook of Agile Software Craftsmanship
** Robert C. Martin
** Rating: 4.37 / 8405
** Description
Even bad code can function. But if code isn t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn t have to be that way.  Noted software expert Robert C. Martin presents a revolutionary paradigm with  Clean Code: A Handbook of Agile Software Craftsmanship . Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleani

* Click: The Magic of Instant Connections
** Ori Brafman
** Rating: 3.69 / 1919
** Description
You know the feeling. You meet someone new—at a party or at work—and you just hit it off. There is an instant sense of camaraderie.   In a word, you “click.”   From the bestselling authors of Sway, Click is a fascinating psychological investigation of the forces behind what makes us click with certain people, or become fully immersed in whatever activity or situation we’re involved in.      From two co-workers who fall head

* Clutterfree
** Leo Babauta
** Rating: 3.68 / 164
** Description
Clutterfree is about creating more time and space by eliminating the clutter in your home and life. By understanding why you have so much stuff, you can start to let it go and enjoy the best that life has to offer.

* Code Complete
** Steve McConnell
** Rating: 4.28 / 6732
** Description
Drawing its examples from a variety of computer languages, this book focuses on programming technique rather than the requirements of a specific programming language or environment. Steve McConnell developed True Type and Windows for the Microsoft Corporation.

* Collected Fictions
** Jorge Luis Borges
** Rating: 4.58 / 16972
** Description
Jorge Luis Borges has been called the greatest Spanish-language writer of our century. Now for the first time in English, all of Borges' dazzling fictions are gathered into a single volume, brilliantly translated by Andrew Hurley. From his 1935 debut with The Universal History of Iniquity, through his immensely influential collections Ficciones and The Aleph, these enigmatic, elaborate, imaginative inventions display Borges' talent for turning fiction on its head by playing with form and genre a

* Confessions of a Public Speaker
** Scott Berkun
** Rating: 3.91 / 3361
** Description
In this hilarious and highly practical book, author and professional speaker Scott Berkun reveals the techniques behind what great communicators do, and shows how anyone can learn to use them well. For managers and teachers -- and anyone else who talks and expects someone to listen -- Confessions of a Public Speaker provides an insider's perspective on how to effectively present ideas to anyone. It's a unique, entertaining, and instructional romp through the embarrassments and triumphs Sc

* Continuous Delivery: Reliable Software Releases Through Build, Test, and Deployment Automation
** Jez Humble
** Rating: 4.15 / 2041
** Description
Winner of the 2011 Jolt Excellence Award!   Getting software released to users is often a painful, risky, and time-consuming process. This groundbreaking new book sets out the principles and technical practices that enable rapid, incremental delivery of high quality, valuable new functionality to users. Through automation of the build, deployment, and testing process, and improved collaboration between developers, testers, and operations, delivery teams can get changes release

* Corporate Confidential: 50 Secrets Your Company Doesn't Want You to Know---and What to Do About Them
** Cynthia Shapiro
** Rating: 3.91 / 400
** Description
Cynthia Shapiro is a former Human Resources executive who's pulling back the curtain on the way that companies really work. In Corporate Confidential, she unmasks startling truths and what you can do about them, including:  * There's no right to free speech in the workplace. *Age discrimination exists. * Why being too smart is not too smart. * Human Resources is not there to help you, but to protect the company from you. * And forty-five more!Crime and Punishment put Dostoevsky at the forefront of Russian writers when it appeared in 1866 and is now one of the most famous and influential novels in world literature.  The poverty-stricken Raskolnikov, a talented student, devises a theory about extraordinary men being above the law, since in their brilliance

* Crucial Conversations: Tools for Talking When Stakes Are High
** Kerry Patterson
** Rating: 3.99 / 30760
** Description
Learn how to keep your cool and get the results you want when emotions flare.  When stakes are high, opinions vary, and emotions run strong, you have three choices: Avoid a crucial conversation and suffer the consequences; handle the conversation badly and suffer the consequences; or read Crucial Conversations and discover how to communicate best when it matters most. Crucial Conversations gives you the tools you need to step up to life's most difficult and important conversations, say

* Crucial Conversations: Tools for Talking When Stakes Are High
** Kerry Patterson
** Rating: 3.99 / 30760
** Description
Learn how to keep your cool and get the results you want when emotions flare.  When stakes are high, opinions vary, and emotions run strong, you have three choices: Avoid a crucial conversation and suffer the consequences; handle the conversation badly and suffer the consequences; or read Crucial Conversations and discover how to communicate best when it matters most. Crucial Conversations gives you the tools you need to step up to life's most difficult and important conversations, say

* Crush It!: Why Now Is the Time to Cash In on Your Passion
** Gary Vaynerchuk
** Rating: 3.86 / 19084
** Description
Do you have a hobby you wish you could indulge in all day? An obsession that keeps you up at night? Now is the perfect time to take that passion and make a living doing what you love. In Crush It! Why NOW Is the Time to Cash In on Your Passion, Gary Vaynerchuk shows you how to use the power of the Internet to turn your real interests into real businesses. Gary spent years building his family business from a local wine shop into a national industry leader. Then one day he turned on a vid

* Cutting for Stone
** Abraham Verghese
** Rating: 4.28 / 287479
** Description
An unforgettable journey into one man's remarkable life, and an epic story about the power, intimacy, and curious beauty of the work of healing others set in 1960s &amp; 1970s Ethiopia and 1980s America.  Marion and Shiva Stone are twin brothers born of a secret union between a beautiful Indian nun and a brash British surgeon at a mission hospital in Addis Ababa. Orphaned by their mother’s death in childbirth and their father’s disappearance, bound together by a preternatural connectio

* Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead
** Brené Brown
** Rating: 4.23 / 59247
** Description
Researcher and thought leader Dr. Brené Brown offers a powerful new vision that encourages us to dare greatly: to embrace vulnerability and imperfection, to live wholeheartedly, and to courageously engage in our lives.   “It is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better. The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood; who st

* David and Goliath: Underdogs, Misfits, and the Art of Battling Giants
** Malcolm Gladwell
** Rating: 3.90 / 105240
** Description
In his #1 bestselling books The Tipping Point, Blink, and Outliers, Malcolm Gladwell has explored the ways we understand and change our world. Now he looks at the complex and surprising ways the weak can defeat the strong, the small can match up against the giant, and how our goals (often culturally determined) can make a huge difference in our ultimate sense of success. Drawing upon examples from the world of business, sports, culture, cutting-edge psychology, and an array

* Death of a Salesman
** Arthur Miller
** Rating: 3.49 / 150456
** Description
'For a salesman, there is no rock bottom to life. He don't put a bolt to a nut, he don't tell you the law or give you medicine. He's a man way out there in the blue, riding on a smile and a shoeshine.'  Willy Loman has been a salesman for 34 years. At 60, he is cast aside, his usefulness exhausted. With no future to dream about he must face the crushing disappointments of his past. He takes one final brave action, but is he heroic at last or a self-deluding fool?  This

* Delivering Happiness: A Path to Profits, Passion, and Purpose
** Tony Hsieh
** Rating: 4.00 / 41451
** Description
You want to learn about the path that we took at Zappos to get to over $1 billion in gross merchandise sales in less than ten years. You want to learn about the path I took that eventually led me to Zappos, and the lessons I learned along the way. You want to learn from all the mistakes we made at Zappos over the years so that your business can avoid making some of the same ones. You want to figure out the right balance of profits, passion, and purpose in business and in life. You want to build

* Design Patterns: Elements of Reusable Object-Oriented Software
** Erich Gamma
** Rating: 4.16 / 7704
** Description
Capturing a wealth of experience about the design of object-oriented software, four top-notch designers present a catalog of simple and succinct solutions to commonly occurring design problems. Previously undocumented, these 23 patterns allow designers to create more flexible, elegant, and ultimately reusable designs without having to rediscover the design solutions themselves.  The authors begin by describing what patterns are and how they can help you design object-oriented software.

* Diary of a Wimpy Kid (Diary of a Wimpy Kid, #1)
** Jeff Kinney
** Rating: 3.96 / 280546
** Description
Boys don’t keep diaries—or do they?  The launch of an exciting and innovatively illustrated new series narrated by an unforgettable kid every family can relate to  It’s a new school year, and Greg Heffley finds himself thrust into middle school, where undersized weaklings share the hallways with kids who are taller, meaner, and already shaving. The hazards of growing up before you’re ready are uniquely revealed through words and drawings as Greg records them in

* Do Androids Dream of Electric Sheep?
** Philip K. Dick
** Rating: 4.08 / 253587
** Description
It was January 2021, and Rick Deckard had a license to kill. Somewhere among the hordes of humans out there, lurked several rogue androids. Deckard's assignment--find them and then..."retire" them. Trouble was, the androids all looked exactly like humans, and they didn't want to be found!

* Do More Faster: Techstars Lessons to Accelerate Your Startup
** David G. Cohen
** Rating: 3.90 / 2256
** Description
Practical advice from some of today's top early stage investors and entrepreneurs TechStars is a mentorship-driven startup accelerator with operations in three U.S. cities. Once a year in each city, it funds about ten Internet startups with a small amount of capital and surrounds them with around fifty top Internet entrepreneurs and investors. Historically, about seventy-five percent of the companies that go through TechStars raise a meaningful amount of angel or venture capital. Do Mo

* Doctor Zhivago
** Boris Pasternak
** Rating: 4.03 / 67056
** Description
This epic tale about the effects of the Russian Revolution and its aftermath on a bourgeois family was not published in the Soviet Union until 1987. One of the results of its publication in the West was Pasternak's complete rejection by Soviet authorities; when he was awarded the Nobel Prize for Literature in 1958 he was compelled to decline it. The book quickly became an international best-seller.  Dr. Yury Zhivago, Pasternak's alter ego, is a poet, philosopher, and physician whose li

* Domain-Driven Design: Tackling Complexity in the Heart of Software
** Eric Evans
** Rating: 4.14 / 2756
** Description
"Eric Evans has written a fantastic book on how you can make the design of your software match your mental model of the problem domain you are addressing. "His book is very compatible with XP. It is not about drawing pictures of a domain; it is about how you think of it, the language you use to talk about it, and how you organize your software to reflect your improving understanding of it. Eric thinks that learning about your problem domain is as likely to happen at the end of your project as at

* Don't Make Me Think!: a Common Sense Approach to Web Usability
** Steve Krug
** Rating: 4.24 / 15258
** Description
PLEASE PROVIDE COURSE INFORMATION PLEASE PROVIDE

* Don't Sweat the Small Stuff ... and it's all small stuff: Simple Ways to Keep the Little Things from Taking Over Your Life
** Richard Carlson
** Rating: 3.95 / 68017
** Description
Don't Sweat the Small Stuff... and it's all small stuff is a book that shows you how to keep from letting the little things in life drive you crazy. In thoughtful and insightful language, author Richard Carlson reveals ways to calm down in the midst of your incredibly hurried, stress-filled life. You can learn to put things in perspective by making the small daily changes he suggests,including advice such as "Think of your problems as potential teachers"; "Remember that when you die, your 'In' b

* East of Eden
** John Steinbeck
** Rating: 4.35 / 343135
** Description
Set in the rich farmland of California’s Salinas Valley, this sprawling and often brutal novel follows the intertwined destinies of two families—the Trasks and the Hamiltons—whose generations helplessly reenact the fall of Adam and Eve and the poisonous rivalry of Cain and Abel. Here Steinbeck created some of his most memorable characters and explored his most enduring themes: the mystery of identity; the inexplicability of love; and the murderous consequences of love’s absence.

* End the Fed
** Ron Paul
** Rating: 4.05 / 4869
** Description
In the post-meltdown world, it is irresponsible, ineffective, and ultimately useless to have a serious economic debate without considering and challenging the role of the Federal Reserve.  Most people think of the Fed as an indispensable institution without which the country's economy could not properly function. But in END THE FED, Ron Paul draws on American history, economics, and fascinating stories from his own long political life to argue that the Fed is both corrupt and unconstit

* Energy at the Crossroads: Global Perspectives and Uncertainties
** Vaclav Smil
** Rating: 3.99 / 72
** Description
In Energy at the Crossroads, Vaclav Smil considers the twenty-first century's crucial question: how to reconcile the modern world's unceasing demand for energy with the absolute necessity to preserve the integrity of the biosphere. With this book he offers a comprehensive, accessible guide to today's complex energy issues -- how to think clearly and logically about what is possible and what is desirable in our energy future.  After a century of unprecedented production growth, t

* Energy: A Beginner's Guide
** Vaclav Smil
** Rating: 3.84 / 321
** Description
As Einstein pointed out in his famous equation, E=MC2, all matter can be described as energy. It is everywhere; it is everything. In this engaging book, prolific author and academic Vaclav Smil provides an introduction to the far-reaching term and gives the reader a greater understanding of energy's place in both past and present society. Starting with an explanation of the concept, he goes on to cover such exciting topics as the inner workings of the human body, and the race for more efficient

* Enriching the Earth: Fritz Haber, Carl Bosch, and the Transformation of World Food Production
** Vaclav Smil
** Rating: 4.09 / 44
** Description
The industrial synthesis of ammonia from nitrogen and hydrogen has been of greater fundamental importance to the modern world than the invention of the airplane, nuclear energy, space flight, or television. The expansion of the world's population from 1.6 billion people in 1900 to today's six billion would not have been possible without the synthesis of ammonia.  In Enriching the Earth, Vaclav Smil begins with a discussion of nitrogen's unique status in the biosphere, its role i

* Escape from Cubicle Nation: From Corporate Prisoner to Thriving Entrepreneur
** Pamela Slim
** Rating: 3.78 / 3437
** Description
Despite grim headlines about the economy, you DON'T have to stay in a job you intensely hate. There's a better opportunity waiting out there, and escaping from cubicle nation is easier than you think.   Pamela Slim spent a decade traveling all over the country as a self-employed trainer for large corporations. She was surprised to find that many of the most successful employees at these companies harbored secret dreams of breaking out to start their own business. They would pull her as

* Evil Plans: Having Fun on the Road to World Domination
** Hugh MacLeod
** Rating: 3.86 / 1112
** Description


* Fahrenheit 451
** Ray Bradbury
** Rating: 3.97 / 1205176
** Description
Fahrenheit 451: la temperatura a la que el papel se enciende y arde. Guy Montag es un bombero y el trabajo de un bombero es quemar libros, que están prohibidos porque son causa de discordia y sufrimiento.El Sabueso Mecánico del Departamento de Incendios, armado con una letal inyección hipodérmica, escoltado por helicópteros, está preparado para rastrear a los disidentes que aún conservan y leen libros. Como 1984, de George Orwell, como Un mundo feliz, de Aldous Huxley, Fahrenheit 451 describe un

* Fascinate: Unlocking the Secret Triggers of Influence, Persuasion, and Captivation
** Sally Hogshead
** Rating: 3.75 / 2423
** Description
What triggers fascination, and how do companies, people, and ideas put those triggers to use?  Why are you captivated by some people but not by others? Why do you recall some brands yet forget the rest? In a distracted, overcrowded world, how do certain leaders, friends, and family members convince you to change your behavior? Fascination: the most powerful way to influence decision making. It's more persuasive than marketing, advertising, or any other form of communication. And it all

* Fear and Loathing in Las Vegas
** Hunter S. Thompson
** Rating: 4.08 / 247112
** Description
Fear and Loathing in Las Vegas is the best chronicle of drug-soaked, addle-brained, rollicking good times ever committed to the printed page. It is also the tale of a long weekend road trip that has gone down in the annals of American pop culture as one of the strangest journeys ever undertaken.

* Fear and Trembling
** Søren Kierkegaard
** Rating: 4.01 / 13966
** Description
Soren Kierkegaard was a Danish philosopher, theologian and religious author interested in human psychology. He is regarded as a leading pioneer of existentialism and one of the greatest philosophers of the 19th Century.  In Fear and Trembling, Kierkegaard wanted to understand the anxiety that must have been present in Abraham when God commanded him to offer his son as a human sacrifice. Abraham had a choice to complete the task or to forget it. He resigned himself to the loss of

* Fieldwork
** Mischa Berlinski
** Rating: 3.60 / 3432
** Description
A daring, spellbinding tale of anthropologists, missionaries, demon possession, sexual taboos, murder, and an obsessed young reporter named Mischa Berlinski.  When his girlfriend takes a job as a schoolteacher in northern Thailand, Mischa Berlinski goes along for the ride, working as little as possible for one of Thailand’s English-language newspapers. One evening a fellow expatriate tips him off to a story. A charismatic American anthropologist, Martiya van der Leun, has been found de

* Fight Club
** Chuck Palahniuk
** Rating: 4.20 / 395968
** Description
Every weekend, in basements and parking lots across the country, young men with good white-collar jobs and absent fathers take off their shoes and shirts and fight each other barehanded for as long as they have to. Then they go back to those jobs with blackened eyes and loosened teeth and the sense that they can handle anything. Fight Club is the invention of Tyler Durden, projectionist, waiter and dark, anarchic genius. And it's only the beginning of his plans for revenge on a world where cance

* First, Break All the Rules: What the World's Greatest Managers Do Differently
** Marcus Buckingham
** Rating: 3.91 / 28815
** Description
Gallup presents the remarkable findings of its revolutionary study of more than 80,000 managers in First, Break All the Rules, revealing what the world’s greatest managers do differently. With vital performance and career lessons and ideas for how to apply them, it is a must-read for managers at every level.

* Flatland: A Romance of Many Dimensions
** Edwin A. Abbott
** Rating: 3.81 / 40580
** Description
This masterpiece of science (and mathematical) fiction is a delightfully unique and highly entertaining satire that has charmed readers for more than 100 years. The work of English clergyman, educator and Shakespearean scholar Edwin A. Abbott (1838-1926), it describes the journeys of A. Square, a mathematician and resident of the two-dimensional Flatland, where women-thin, straight lines-are the lowliest of shapes, and where men may have any number of sides, depending on their social status.Fooled by Randomness is a standalone book in Nassim Nicholas Taleb’s landmark Incerto series, an investigation of opacity, luck, uncertainty, probability, human error, risk, and decision-making in a world we don’t understand. The other books in the series are The Black Swan, Antifragile,and The Bed of Procrustes.

* For Whom the Bell Tolls
** Ernest Hemingway
** Rating: 3.96 / 210051
** Description
Librarian's note: An alternate cover edition can be found here  In 1937 Ernest Hemingway traveled to Spain to cover the civil war there for the North American Newspaper Alliance. Three years later he completed the greatest novel to emerge from "the good fight", For Whom the Bell Tolls.   The story of Robert Jordan, a young American in the International Brigades attache

* Foundation (Foundation #1)
** Isaac Asimov
** Rating: 4.13 / 305957
** Description
For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. But only Hari Seldon, creator of the revolutionary science of psychohistory, can see into the future -- to a dark age of ignorance, barbarism, and warfare that will last thirty thousand years. To preserve knowledge and save mankind, Seldon gathers the best minds in the Empire -- both scientists and scholars -- and brings them to a bleak planet at the edge of the Galaxy to serve as a beacon of hope for a future gene

* Frommer's 500 Adrenaline Adventures
** Lois Friedland
** Rating: 3.77 / 13
** Description
Frommer's 500 Best Adrenaline Adventures features high-octane experiences for both passionate travelers and adventure seekers. From dare-devil sports to hair-raising haunted houses to wacky and obscure festivals and races, Frommer's offers ideas for a wide variety of adventures. Chapters include: In the Air: Hangliding, Bungee Jumping &amp; Ziplining  On the Water: Diving, Snorkeling &amp; Whitewater Rafting  Mountains &amp; Canyons: Skiing, Snowboarding, Climbing &amp; Hikin

* Gamestorming: A Playbook for Innovators, Rule-breakers, and Changemakers
** Dave  Gray
** Rating: 3.94 / 3953
** Description


* Getting Everything You Can Out of All You've Got: 21 Ways You Can Out-Think, Out-Perform, and Out-Earn the Competition
** Jay Abraham
** Rating: 3.98 / 5470
** Description
A trusted advisor to America's top corporations and recognized as one of today's preeminent marketing experts, Jay Abraham has created a program of proven strategies to help you realize undreamed-of success! Unseen opportunities face each of us every day. Using clear examples from his own experience, Jay explains just how easy it can be to find and/or create new opportunities for wealth-building in any existing business, enterprise, or venture.  And just how easy can it be? One entrepr

* Getting Real: The Smarter, Faster, Easier Way to Build a Web Application
** 37 Signals
** Rating: 4.03 / 6412
** Description

* Getting Started in Consulting
** Alan Weiss
** Rating: 3.86 / 1752
** Description
A new revision of the successful guidebook for novice consultants  Getting Started in Consulting, Second Edition provides practical solutions and proven strategies for launching a consulting business. Readers will learn how low overhead and a high degree of organization can translate into a six-figure income working from a home office. The book also offers key information on how to finance a consulting practice, how to write proposals, how to set up billing and bookkeeping, and more. A new

* Getting Things Done: The Art of Stress-Free Productivity
** David    Allen
** Rating: 3.99 / 85589
** Description
With first-chapter allusions to martial arts, "flow," "mind like water," and other concepts borrowed from the East (and usually mangled), you'd almost think this self-helper from David Allen should have been called Zen and the Art of Schedule Maintenance. Not quite. Yes, Getting Things Done offers a complete system for downloading all those free-floating gotta-do's clogging your brain into a sophisticated framework of files and action lists--all purportedly to free your mind to

* Global Catastrophes and Trends: The Next Fifty Years
** Vaclav Smil
** Rating: 3.89 / 93
** Description
Fundamental change occurs most often in one of two ways: as a "fatal discontinuity," a sudden catastrophic event that is potentially world changing, or as a persistent, gradual trend. Global catastrophes include volcanic eruptions, viral pandemics, wars, and large-scale terrorist attacks; trends are demographic, environmental, economic, and political shifts that unfold over time. In this provocative book, scientist Vaclav Smil takes a wide-ranging, interdisciplinary look at the catastrophes and

* Gone Girl
** Gillian Flynn
** Rating: 4.04 / 1669984
** Description
On a warm summer morning in North Carthage, Missouri, it is Nick and Amy Dunne’s fifth wedding anniversary. Presents are being wrapped and reservations are being made when Nick’s clever and beautiful wife disappears. Husband-of-the-Year Nick isn’t doing himself any favors with cringe-worthy daydreams about the slope and shape of his wife’s head, but passages from Amy's diary reveal the alpha-girl perfectionist could have put anyone dangerously on edge. Under mounting pressure from the police and

* Gone with the Wind
** Margaret Mitchell
** Rating: 4.28 / 913800
** Description
Gone with the Wind is a novel written by Margaret Mitchell, first published in 1936. The story is set in Clayton County, Georgia, and Atlanta during the American Civil War and Reconstruction era. It depicts the struggles of young Scarlett O'Hara, the spoiled daughter of a well-to-do plantation owner, who must use every means at her disposal to claw her way out of the poverty she finds herself in after Sherman's March to the Sea. A historical novel, the story is a Bildungsroman or coming-o

* Good to Great: Why Some Companies Make the Leap... and Others Don't
** James C. Collins
** Rating: 4.05 / 90157
** Description
To find the keys to greatness, Collins's 21-person research team read and coded 6,000 articles, generated more than 2,000 pages of interview transcripts and created 384 megabytes of computer data in a five-year project. The findings will surprise many readers and, quite frankly, upset others.  The Challenge Built to Last, the defining management study of the nineties, showed how great companies triumph over time and how long-term sustained performance can be engineered into the DN

* Goodnight Moon
** Margaret Wise Brown
** Rating: 4.27 / 255133
** Description
In a great green room, tucked away in bed, is a little bunny. "Goodnight room, goodnight moon." And to all the familiar things in the softly lit room -- to the picture of the three little bears sitting on chairs, to the clocks and his socks, to the mittens and the kittens, to everything one by one -- the little bunny says goodnight.  In this classic of children's literature, beloved by generations of readers and listeners, the quiet poetry of the words and the gentle, lulling illustrat

* Gravity's Rainbow
** Thomas Pynchon
** Rating: 4.03 / 28904
** Description
Winner of the 1973 National Book Award, Gravity's Rainbow is a postmodern epic, a work as exhaustively significant to the second half of the 20th century as Joyce's Ulysses was to the first. Its sprawling, encyclopedic narrative and penetrating analysis of the impact of technology on society make it an intellectual tour de force.

* Great by Choice: Uncertainty, Chaos, and Luck--Why Some Thrive Despite Them All
** James C. Collins
** Rating: 4.08 / 11993
** Description
 The new question: Ten years after the worldwide bestseller "Good to Great," Jim Collins returns to ask: Why do some companies thrive in uncertainty, even chaos, and others do not? In "Great by Choice," Collins and his colleague, Morten T. Hansen, enumerate the principles for building a truly great enterprise in unpredictable, tumultuous, and fast-moving times.  The new study: "Great by Choice" distinguishes itself from Collins's prior work by its focus on the type of unstable environm

* Gödel's Proof
** Ernest Nagel
** Rating: 4.14 / 3733
** Description
In 1931 Kurt Godel published his fundamental paper, "On Formally Undecidable Propositions of Principia Mathematica and Related Systems." This revolutionary paper challenged certain basic assumptions underlying much research in mathematics and logic. Godel received public recognition of his work in 1951 when he was awarded the first Albert Einstein Award for achievement in the natural sciences--perhaps the highest award of its kind in the United States. The award committee described his wo

* DONE Hackers & Painters: Big Ideas from the Computer Age
  CLOSED: [2017-11-24 Fri 03:02]
** Paul Graham
** Rating: 4.06 / 6266
** Description
“The computer world is like an intellectual Wild West, in which you can shoot anyone you wish with your ideas, if you’re willing to risk the consequences.” —from Hackers &amp; Painters: Big Ideas from the Computer Age, by Paul Graham  We are living in the computer age, in a world increasingly designed and engineered by computer programmers and software designers, by people who call themselves hackers. Who are these people, what motivates them, and why should you care?Artists Retreat: Abandon your life for three months'. They are led to believe that here they will leave behind all the distractions of 'real life' that are keeping them from creating the masterpiece that is in them.   But 'here' turns out to be a cavernou

* Head First Design Patterns: A Brain-Friendly Guide
** Eric Freeman
** Rating: 4.24 / 5182
** Description
You're not alone.   At any given moment, somewhere in the world someone struggles with the same software design problems you have. You know you don't want to reinvent the wheel (or worse, a flat tire), so you look to Design Patterns--the lessons learned by those who've faced the same problems. With Design Patterns, you get to take advantage of the best practices and experience of others, so that you can spend your time on...something else. Something more challenging. Something more com

* Heart of Darkness
** Joseph Conrad
** Rating: 3.42 / 316416
** Description
Marlow, a seaman and wanderer, recounts his physical and psychological journey in search of the infamous ivory trader Kurtz. Travelling up river to the heart of the African continent, he gradually becomes obsessed by the enigmatic, wraith-like figure. Marlow's discovery of how Kurtz has gained his position of power over the local people involves him in a radical questioning, not only of his own nature and values, but those of Western civilization. A haunting and hugely influential Modernist mast

* Helter Skelter: The True Story of the Manson Murders
** Vincent Bugliosi
** Rating: 4.00 / 96733
** Description
A national bestseller—7 million copies sold.   Prosecuting attorney in the Manson trial, Vincent Bugliosi held a unique insider's position in one of the most baffling and horrifying cases of the twentieth century: the cold-blooded Tate-LaBianca murders carried out by Charles Manson and four of his followers. What motivated Manson in his seemingly mindless selection of victims, and what was his hold over the young women who obeyed his orders? Here is the gripping story of this fa

* Holy Bible: King James Version
** Anonymous
** Rating: 4.43 / 175370
** Description
This up-to-date version of the universally accepted text from the King James Bible will make a handsome addition to any home. The revised translation is easily accessible for the modern reader, and is based on the original King James Version, published in 1611. In the course of time, the King James Version came to be regarded as "the Authorized Version.” It has been termed the "noblest monument of English prose,” and it has come to be of central importance to Western society as no other book. Th

* How Children Succeed: Grit, Curiosity, and the Hidden Power of Character
** Paul Tough
** Rating: 3.91 / 18448
** Description
Why do some children succeed while others fail?  The story we usually tell about childhood and success is the one about intelligence: Success comes to those who score highest on tests, from preschool admissions to SATs.  But in "How Children Succeed," Paul Tough argues for a very different understanding of what makes a successful child. Drawing on groundbreaking research in neuroscience, economics, and psychology, Tough shows that the qualities that matter most have less to d

* How Will You Measure Your Life?
** Clayton M. Christensen
** Rating: 4.06 / 14416
** Description
In 2010 world-renowned innovation expert Clayton M. Christensen gave a powerful speech to the Harvard Business School's graduating class. Drawing upon his business research, he offered a series of guidelines for finding meaning and happiness in life. He used examples from his own experiences to explain how high achievers can all too often fall into traps that lead to unhappiness.  The speech was memorable not only because it was deeply revealing but also because it came at a time of in

* How the Mind Works
** Steven Pinker
** Rating: 3.97 / 14845
** Description
In this extraordinary bestseller, Steven Pinker, one of the world's leading cognitive scientists, does for the rest of the mind what he did for language in his 1994 book, The Language Instinct. He explains what the mind is, how it evolved, and how it allows us to see, think, feel, laugh, interact, enjoy the arts, and ponder the mysteries of life. And he does it with the wit that prompted Mark Ridley to write in the New York Times Book Review, "No other science writer makes me l

* However Long the Night: Molly Melching's Journey to Help Millions of African Women and Girls Triumph
** Aimee Molloy
** Rating: 4.13 / 695
** Description
In However Long the Night, Aimee Molloy tells the unlikely and inspiring story of Molly Melching, an American woman whose experience as an exchange student in Senegal led her to found Tostan and dedicate almost four decades of her life to the girls and women of Africa.  This moving biography details Melching's beginnings at the University of Dakar and follows her journey of 40 years in Africa, where she became a social entrepreneur and one of humanity's strongest voices for the rights

* Human Action: A Treatise on Economics
** Ludwig von Mises
** Rating: 4.31 / 2773
** Description
Human Action: A Treatise on Economics is the most important book on political economy you will ever own. It was (and remains) the most comprehensive, systematic, forthright, and powerful defense of the economics of liberty ever written.   "Every once in a while the human race pauses in the job of botching its affairs and redeems itself by producing a noble work of the intellect.... To state that Human Action is a must' book is a great understatement. This is the economic

* I Know Why the Caged Bird Sings
** Maya Angelou
** Rating: 4.19 / 293308
** Description
Sent by their mother to live with their devout, self-sufficient grandmother in a small Southern town, Maya and her brother, Bailey, endure the ache of abandonment and the prejudice of the local "powhitetrash." At eight years old and back at her mother’s side in St. Louis, Maya is attacked by a man many times her age—and has to live with the consequences for a lifetime. Years later, in San Francisco, Maya learns that love for herself, the kindness of others, her own strong spirit, and the ideas o

* I, Claudius (Claudius, #1)
** Robert Graves
** Rating: 4.27 / 43037
** Description
From the Autobiography of Tiberius Claudius, Born 10 B.C., Murdered and Deified A.D. 54.   Set in the first century A.D. in Rome and written as an autobiographical memoir, this colorful story of the life of the Roman emperor Claudius stands as one of the modern classics of historical fiction.  Physically weak and afflicted with stuttering, Claudius is initially despised and dismissed as an idiot. Shunted to the background of imperial affairs by his embarrassed royal family, h

* In Cold Blood
** Truman Capote
** Rating: 4.05 / 410722
** Description
On November 15, 1959, in the small town of Holcomb, Kansas, four members of the Clutter family were savagely murdered by blasts from a shotgun held a few inches from their faces. There was no apparent motive for the crime, and there were almost no clues.  As Truman Capote reconstructs the murder and the investigation that led to the capture, trial, and execution of the killers, he generates both mesmerizing suspense and astonishing empathy. In Cold Blood is a work that transcend

* In the Buddha's Words: An Anthology of Discourses from the Pali Canon
** Bhikkhu Bodhi
** Rating: 4.37 / 1998
** Description
The works of the Buddha can feel vast, and it is sometimes difficult for even longtime students to know where to look, especially since the Buddha never explicitly defined the framework behind his teachings. Designed to provide just such a framework, In the Buddha's Words is an anthology of the Buddha's works that has been specifically compiled by a celebrated scholar and translator. For easy reference, the book is arrayed in ten thematic sections ranging from "The Human Condition" to "Ma

* In the Plex: How Google Thinks, Works, and Shapes Our Lives
** Steven Levy
** Rating: 3.83 / 21060
** Description
Written with full cooperation from top management, including cofounders Sergey Brin and Larry Page, this is the inside story behind Google, the most successful and most admired technology company of our time, told by one of our best technology writers.  Few companies in history have ever been as successful and as admired as Google, the company that has transformed the Internet and become an indispensable part of our lives. How has Google done it? Veteran technology reporter Steven Levy

* Innovation and Entrepreneurship: Practice and Principles
** Peter F. Drucker
** Rating: 4.03 / 6534
** Description
The first book to present innovation and entrepreneurship as a purposeful and systematic discipline, this classic business title explains and analyzes the challenges and opportunities of America's entrepreneurial economy.

* Inspired: How To Create Products Customers Love
** Marty Cagan
** Rating: 4.14 / 4025
** Description

* Interpreter of Maladies
** Jhumpa Lahiri
** Rating: 4.12 / 128249
** Description
Navigating between the Indian traditions they've inherited and the baffling new world, the characters in Jhumpa Lahiri's elegant, touching stories seek love beyond the barriers of culture and generations. In "A Temporary Matter," published in The New Yorker, a young Indian-American couple faces the heartbreak of a stillborn birth while their Boston neighborhood copes with a nightly blackout. In the title story, an interpreter guides an American family through the India of their ancestors

* Into the Wild
** Jon Krakauer
** Rating: 3.95 / 683063
** Description
Librarian's Note: An alternate cover edition can be found here  In April 1992 a young man from a well-to-do family hitchhiked to Alaska and walked alone into the wilderness north of Mt. McKinley. His name was Christopher Johnson McCandless. He had given $25,000 in savings to charity, abandoned his car and most of his possessions, burned all the cash in his wallet, and invented a new life

* Invisible Man
** Ralph Ellison
** Rating: 3.84 / 130024
** Description
First published in 1952 and immediately hailed as a masterpiece, Invisible Man is one of those rare novels that have changed the shape of American literature. For not only does Ralph Ellison's nightmare journey across the racial divide tell unparalleled truths about the nature of bigotry and its effects on the minds of both victims and perpetrators, it gives us an entirely new model of what a novel can be.  As he journeys from the Deep South to the streets and basements of Harle

* It
** Stephen King
** Rating: 4.19 / 517747
** Description
Welcome to Derry, Maine…  It’s a small city, a place as hauntingly familiar as your own hometown. Only in Derry the haunting is real…  They were seven teenagers when they first stumbled upon the horror. Now they are grown-up men and women who have gone out into the big world to gain success and happiness. But none of them can withstand the force that has drawn them back to Derry to face the nightmare without an end, and the evil without a name.

* It's Not Luck
** Eliyahu M. Goldratt
** Rating: 4.07 / 1485
** Description

* Japan's Dietary Transition and Its Impacts
** Vaclav Smil
** Rating: 3.64 / 14
** Description
In a little more than a century, the Japanese diet has undergone a dramatic transformation. In 1900, a plant-based, near-subsistence diet was prevalent, with virtually no consumption of animal protein. By the beginning of the twenty-first century, Japan's consumption of meat, fish, and dairy had increased markedly (although it remained below that of high-income Western countries). This dietary transition was a key aspect of the modernization that made Japan the world's second largest economic po

* Jimmy Corrigan, the Smartest Kid on Earth
** Chris Ware
** Rating: 4.10 / 19385
** Description
Jimmy Corrigan has rightly been hailed as the greatest graphic novel ever to be published. It won the Guardian First Book Award 2001, the first graphic novel to win a major British literary prize.  It is the tragic autobiography of an office dogsbody in Chicago who one day meets the father who abandoned him as a child. With a subtle, complex and moving story and the drawings that are as simple and original as they are strikingly beautiful, Jimmy Corrigan is a book

* Kafka on the Shore
** Haruki Murakami
** Rating: 4.13 / 202842
** Description
Kafka on the Shore is powered by two remarkable characters: a teenage boy, Kafka Tamura, who runs away from home either to escape a gruesome oedipal prophecy or to search for his long-missing mother and sister; and an aging simpleton called Nakata, who never recovered from a wartime affliction and now is drawn toward Kafka for reasons that, like the most basic activities of daily life, he cannot fathom.  As their paths converge, and the reasons for that convergence become clear,

* Kaizen: The Key to Japan's Competitive Success
** Masaaki Imai
** Rating: 4.06 / 234
** Description
For the professional manager or student of management, a comprehensive handbook of 16 Kaizen management practices that can be put to work. KAIZEN uses more than 100 examples in action and contains 15 corporate case studies.

* Kanban: Successful Evolutionary Change for Your Technology Business
** David J. Anderson
** Rating: 3.97 / 1989
** Description

* Kitchen Confidential: Adventures in the Culinary Underbelly
** Anthony Bourdain
** Rating: 4.00 / 148677
** Description
A deliciously funny, delectably shocking banquet of wild-but-true tales of life in the culinary trade from Chef Anthony Bourdain, laying out his more than a quarter-century of drugs, sex, and haute cuisine—now with all-new, never-before-published material.  New York Chef Tony Bourdain gives away secrets of the trade in his wickedly funny, inspiring memoir/expose. Kitchen Confidential reveals what Bourdain calls "twenty-five years of sex, drugs, bad behavior and haute cuisine."

* Laika
** Nick Abadzis
** Rating: 3.96 / 4612
** Description
From the dog's point of view, follows the adventures of the dog sent into space by the Soviet Union.

* Leading Lean Software Development: Results Are Not the Point
** Mary Poppendieck
** Rating: 4.19 / 261
** Description
Building on their breakthrough bestsellers "Lean Software Development" and "Implementing Lean Software Development," Mary and Tom Poppendieck s latest book shows software leaders and team members exactly how to drive high-value change throughout a software organization and make it stick. They go far beyond generic implementation guidelines, demonstrating exactly how to make lean work in real projects, environments, and companies.  The Poppendiecks organize this book around the crucial conce

* Leaving Microsoft to Change the World: An Entrepreneur's Odyssey to Educate the World's Children
** John Wood
** Rating: 4.07 / 3853
** Description
John Wood discovered his passion, his greatest success, and his life's work—not at business school or leading Microsoft's charge into Asia in the 1990s—but on a soul-searching trip to the Himalayas. Wood felt trapped between an all-consuming career and a desire to do something lasting and significant. Stressed from the demands of his job, he took a vacation trekking in Nepal because a friend had told him, "If you get high enough in the mountains, you can't hear Steve Ballmer yelling at you anymo

* Life After Life
** Kate Atkinson
** Rating: 3.74 / 161671
** Description
What if you could live again and again, until you got it right?   On a cold and snowy night in 1910, Ursula Todd is born to an English banker and his wife. She dies before she can draw her first breath. On that same cold and snowy night, Ursula Todd is born, lets out a lusty wail, and embarks upon a life that will be, to say the least, unusual. For as she grows, she also dies, repeatedly, in a variety of ways, while the young century marches on towards its second cataclysmic world war.

* Linchpin: Are You Indispensable?
** Seth Godin
** Rating: 3.87 / 29321
** Description
"This is what the future of work (and the world) looks like. Actually, it's already happening around you." — Tony Hsieh, CEO, Zappos.com  In bestsellers such as Purple Cow and Tribes, Seth Godin taught readers how to make remarkable products and spread powerful ideas. But this book is about you—your choices, your future, and your potential to make a huge difference in whatever field you choose.  There used to be two teams in every workplace: management an

* Little House on the Prairie (Little House, #2)
** Laura Ingalls Wilder
** Rating: 4.18 / 206764
** Description
Meet Laura Ingalls . . .  . . . the little girl who would grow up to write the Little House books. Pa Ingalls decides to sell the little log house, and the family sets out for Indian country! They travel from Wisconsin to Kansas and there, finally, Pa builds their little house on the prairie. Sometimes farm life is difficult, even dangerous, but Laura and the family are kept busy and are happy with the promise of their new life on the prairie. Laura and her family journey we

* Lolita
** Vladimir Nabokov
** Rating: 3.88 / 526956
** Description
Humbert Humbert - scholar, aesthete and romantic - has fallen completely and utterly in love with Lolita Haze, his landlady's gum-snapping, silky skinned twelve-year-old daughter. Reluctantly agreeing to marry Mrs Haze just to be close to Lolita, Humbert suffers greatly in the pursuit of romance; but when Lo herself starts looking for attention elsewhere, he will carry her off on a desperate cross-country misadventure, all in the name of Love. Hilarious, flamboyant, heart-breaking and full of in

* Lonesome Dove
** Larry McMurtry
** Rating: 4.47 / 118616
** Description
A love story, an adventure, and an epic of the frontier, Larry McMurtry’s Pulitzer Prize— winning classic, Lonesome Dove, the third book in the Lonesome Dove tetralogy, is the grandest novel ever written about the last defiant wilderness of America.  Journey to the dusty little Texas town of Lonesome Dove and meet an unforgettable assortment of heroes and outlaws, whores and ladies, Indians and settlers. Richly authentic, beautifully written, always dramatic, Lonesome

* Long Walk to Freedom
** Nelson Mandela
** Rating: 4.31 / 48961
** Description
The book that inspired the major new motion picture Mandela: Long Walk to Freedom.  Nelson Mandela is one of the great moral and political leaders of our time: an international hero whose lifelong dedication to the fight against racial oppression in South Africa won him the Nobel Peace Prize and the presidency of his country. Since his triumphant release in 1990 from more than a quarter-century of imprisonment, Mandela has been at the center of the most compelling and ins

* Looking for Alaska
** John Green
** Rating: 4.08 / 855414
** Description
Before. Miles “Pudge” Halter is done with his safe life at home. His whole life has been one big non-event, and his obsession with famous last words has only made him crave “the Great Perhaps” even more (Francois Rabelais, poet). He heads off to the sometimes crazy and anything-but-boring world of Culver Creek Boarding School, and his life becomes the opposite of safe. Because down the hall is Alaska Young. The gorgeous, clever, funny, sexy, self-destructive, screwed up, and utterly fasci

* Lord of the Flies
** William Golding
** Rating: 3.65 / 1710157
** Description
When a plane crashes on a remote island, a small group of schoolboys are the sole survivors. From the prophetic Simon and virtuous Ralph to the lovable Piggy and brutish Jack, each of the boys attempts to establish control as the reality - and brutal savagery - of their situation sets in.  The boys' struggle to find a way of existing in a community with no fixed boundaries invites readers to evaluate the concepts involved in social and political constructs and moral frameworks. Ideas o

* DONE Love Is a Dog from Hell
  CLOSED: [2017-11-24 Fri 03:06]
** Charles Bukowski
** Rating: 4.16 / 21198
** Description
Poems rising from and returning to Bukowski's personal experiences reflect people, objects, places, and events of the external world, and reflects on them, on their way out and back.

* Love Medicine
** Louise Erdrich
** Rating: 3.98 / 17376
** Description
Set on and around a North Dakota reservation, ‘Love Medicine’ tells the story of the Lamartines and the Kashpaws – two extraordinary families whose fates are united and sustained in a harsh world by the strength and diversity of their love.  We meet the sensual Lulu Lamartine, whose children have different fathers, but whose passionate tie to her first love, Nector Kashpaw, intensifies over the years; June Kashpaw, who froze to death in a snowstorm; and the philosophical Lipsha Morriss

* Love in the Time of Cholera
** Gabriel García Márquez
** Rating: 3.89 / 328782
** Description
In their youth, Florentino Ariza and Fermina Daza fall passionately in love. When Fermina eventually chooses to marry a wealthy, well-born doctor, Florentino is devastated, but he is a romantic. As he rises in his business career he whiles away the years in 622 affairs--yet he reserves his heart for Fermina. Her husband dies at last, and Florentino purposefully attends the funeral. Fifty years, nine months, and four days after he first declared his love for Fermina, he will do so again.

* Lucky or Smart?: Secrets to an Entrepreneurial Life
** Bo Peabody
** Rating: 3.76 / 570
** Description
At twenty-seven, Bo Peabody was an Internet multi-millionaire. In the heady days of the late 1990s, though, when every cool kid had an IPO, that wasn’t very remarkable. What is remarkable is that he’s even more successful today. He has co-founded five different companies, in varied industries, and made them thrive during the best and worst of economic times. Through it all, the one question everyone asks is: Was it his smarts that made him an entrepreneurial leader, or was it just plain luck? Th

* Ludwig Wittgenstein: The Duty of Genius
** Ray Monk
** Rating: 4.34 / 3250
** Description
"Great philosophical biographies can be counted on one hand. Monk's life of Wittgenstein is such a one."--"The Christian Science Monitor."

* Making Things Happen: Mastering Project Management
** Scott Berkun
** Rating: 4.00 / 3537
** Description
In the updated edition of this critically acclaimed and bestselling book, Microsoft project veteran Scott Berkun offers a collection of essays on field-tested philosophies and strategies for defining, leading, and managing projects. Each essay distills complex concepts and challenges into practical nuggets of useful advice, and the new edition now adds more value for leaders and managers of projects everywhere.   Based on his nine years of experience as a program manager for Internet E

* Man's Search for Meaning
** Viktor E. Frankl
** Rating: 4.33 / 204776
** Description
Psychiatrist Viktor Frankl's memoir has riveted generations of readers with its descriptions of life in Nazi death camps and its lessons for spiritual survival. Between 1942 and 1945 Frankl labored in four different camps, including Auschwitz, while his parents, brother, and pregnant wife perished. Based on his own experience and the experiences of others he treated later in his practice, Frankl argues that we cannot avoid suffering but we can choose how to cope with it, find meaning in it, and

* Manage Your Day-to-Day: Build Your Routine, Find Your Focus, and Sharpen Your Creative Mind
** Jocelyn K. Glei
** Rating: 3.88 / 10734
** Description
Do you work at a breakneck pace all day, only to find that you haven't accomplished the most important things on your agenda by the time you leave the office? With wisdom from 20 leading creative minds, 99U's Manage Your Day-to-Day will equip you with pragmatic insights for using your time wisely and making your best work. We'll show you how to build a rock-solid daily routine, field a constant barrage of messages, find focus amidst chaos, and carve out the time you need to do the work that matt

* Management 3.0: Leading Agile Developers, Developing Agile Leaders
** Jurgen Appelo
** Rating: 4.14 / 1301
** Description

* Managing Humans: Biting and Humorous Tales of a Software Engineering Manager
** Michael Lopp
** Rating: 3.94 / 1824
** Description
The humor and insights in the 2nd Edition ofManaging Humans are drawn from Michael Lopp's management experiences at Apple, Netscape, Symantec, and Borland, among others. This book is full of stories based on companies in the Silicon Valley where people have been known to yell at each other and occasionally throw chairs. It is a place full of dysfunctional bright people who are in an incredible hurry to find the next big thing so they can strike it rich and then do it all over again. Among these

* Maus I: A Survivor's Tale: My Father Bleeds History (Maus, #1)
** Art Spiegelman
** Rating: 4.35 / 197440
** Description
A story of a Jewish survivor of Hitler's Europe and his son, a cartoonist who tries to come to terms with his father's story and history itself.

* Me Talk Pretty One Day
** David Sedaris
** Rating: 3.97 / 522419
** Description
David Sedaris' move to Paris from New York inspired these hilarious pieces, including the title essay, about his attempts to learn French from a sadistic teacher who declares that every day spent with you is like having a caesarean section. His family is another inspiration. You Can't Kill the Rooster is a portrait of his brother, who talks incessant hip-hop slang to his bewildered father. And no one hones a finer fury in response to such modern annoyances as restaurant meals presented in ludicr

* Middlesex
** Jeffrey Eugenides
** Rating: 3.98 / 514923
** Description
Middlesex tells the breathtaking story of Calliope Stephanides, and three generations of the Greek-American Stephanides family, who travel from a tiny village overlooking Mount Olympus in Asia Minor to Prohibition-era Detroit, witnessing its glory days as the Motor City and the race riots of 1967 before moving out to the tree-lined streets of suburban Grosse Pointe, Michigan. To understand why Calliope is not like other girls, she has to uncover a guilty family secret, and the astonishing

* Midnight's Children
** Salman Rushdie
** Rating: 3.99 / 86223
** Description
Alternate covers for this ISBN can be found here and here  Born at the stroke of midnight, at the precise moment of India's independence, Saleem Sinai is destined from birth to be special. For he is one of 1,001 children born in the midnight hour, children who all have special gifts, children w

* Mindfulness in Plain English
** Henepola Gunaratana
** Rating: 4.22 / 8641
** Description
With his distinctive clarity and wit, "Bhante G" takes us step by step through the myths, realities, and benefits of meditation and the practice of mindfulness. We already have the foundation we need to live a more productive and peaceful life — Bhante simply points to each tool of meditation, tells us what it does, and how to make it work. This expanded edition includes the complete text of its bestselling predecessor, as well as a new chapter on the cultivation of loving kindness, an especiall

* Mindset: The New Psychology of Success
** Carol S. Dweck
** Rating: 4.04 / 39642
** Description
Now updated with new research — the book that has changed millions of lives.  After decades of research, world-renowned Stanford University psychologist Carol S. Dweck, Ph.D., discovered a simple but groundbreaking idea: the power of mindset. In this brilliant book, she shows how success in school, work, sports, the arts, and almost every area of human endeavor can be dramatically influenced by how we think about our talents and abilities. People with a fixed mindset — th

* Moneyball: The Art of Winning an Unfair Game
** Michael   Lewis
** Rating: 4.25 / 73085
** Description
Billy Beane, general manager of MLB's Oakland A's and protagonist of Michael Lewis's Moneyball, had a problem: how to win in the Major Leagues with a budget that's smaller than that of nearly every other team. Conventional wisdom long held that big name, highly athletic hitters and young pitchers with rocket arms were the ticket to success. But Beane and his staff, buoyed by massive amounts of carefully interpreted statistical data, believed that wins could be had by more affordable metho

* Musashi
** Eiji Yoshikawa
** Rating: 4.43 / 12103
** Description
The classic samurai novel about the real exploits of the most famous swordsman. Musashi is a novel in the best tradition of Japanese story telling. It is a living story, subtle and imaginative, teeming with memorable characters, many of them historical. Interweaving themes of unrequited love, misguided revenge, filial piety and absolute dedication to the Way of the Samurai, it depicts vividly a world Westerners know only vaguely.

* Naked Economics: Undressing the Dismal Science
** Charles Wheelan
** Rating: 4.00 / 11444
** Description
Naked Economics makes up for all of those Econ 101 lectures you slept through (or avoided) in college, demystifying key concepts, laying bare the truths behind the numbers, and answering those questions you have always been too embarrassed to ask. For all the discussion of Alan Greenspan in the media, does anyone know what the Fed actually does? And what about those blackouts in California? Were they a conspiracy on the part of the power companies? Economics is life. There's no way to u

* Nausea
** Jean-Paul Sartre
** Rating: 3.91 / 62650
** Description
Nausea is the story of Antoine Roquentin, a French writer who is horrified at his own existence. In impressionistic, diary form he ruthlessly catalogues his every feeling and sensation about the world and people around him.   His thoughts culminate in a pervasive, overpowering feeling of nausea which "spread at the bottom of the viscous puddle, at the bottom of our time, the time of purple suspenders and broken chair seats; it is made of wide, soft instants, spreading at

* Nietzsche and Philosophy
** Gilles Deleuze
** Rating: 4.16 / 2888
** Description
First published in 1962, "Nietzsche et la Philosphie" demonstrates, with a rare combination of scholarly rigor and imaginative interpretation, how Friedrich Nietzsche initiated a new mode of philosophical thinking. A landmark, "Nietzsche and Philosophy" is one of the first books to dispute the deep-seated assumption that dialectics provide the only possible basis for radical thought. Deleuze's analysis stands at the beginning of an important avenue of postwar thought - poststructuralism. For thi

* Nietzsche: Philosopher, Psychologist, Antichrist
** Walter Kaufmann
** Rating: 4.20 / 5431
** Description
This classic is the benchmark against which all modern books about Nietzsche are measured. When Walter Kaufmann wrote it in the immediate aftermath of WWII, most scholars outside Germany viewed Nietzsche as part madman, part proto-Nazi &amp; almost wholly unphilosophical. Kaufmann rehabilitated Nietzsche nearly single-handedly, presenting his works as one of the great achievements of Western philosophy. Responding to the powerful myths &amp; countermyths that had sprung up around Nietzsche, Kauf

* No Exit and Three Other Plays
** Jean-Paul Sartre
** Rating: 4.09 / 22884
** Description
In these four plays, Jean-Paul Sartre, the great existentialist novelist and philosopher, displays his mastery of drama. NO EXIT is an unforgettable portrayal of hell. THE FLIES is a modern reworking of the Electra-Orestes story. DIRTY HANDS is about a young intellectual torn between theory and praxis. THE RESPECTFUL PROSTITUTE is an attack on American racism.

* Norwegian Wood
** Haruki Murakami
** Rating: 4.02 / 226005
** Description
Toru, a quiet and preternaturally serious young college student in Tokyo, is devoted to Naoko, a beautiful and introspective young woman, but their mutual passion is marked by the tragic death of their best friend years before. Toru begins to adapt to campus life and the loneliness and isolation he faces there, but Naoko finds the pressures and responsibilities of life unbearable. As she retreats further into her own world, Toru finds himself reaching out to others and drawn to a fiercely indepe

* Notes from Underground, White Nights, The Dream of a Ridiculous Man, and Selections from The House of the Dead
** Fyodor Dostoyevsky
** Rating: 4.17 / 67795
** Description
A collection of powerful stories by one of the masters of Russian literature, illustrating the author's thoughts on political philosophy, religion and above all, humanity: Notes from Underground, White Nights, The Dream of a Ridiculous Man, and Selections from The House of the Dead (150th Anniversary Edition)  The compelling works presented in this volume were written at distinct periods in Dostoyevsky's life, at decisive moments in his groping for a political philosophy and a r

* Numbers Rule Your World: The Hidden Influence of Probabilities and Statistics on Everything You Do
** Kaiser Fung
** Rating: 3.53 / 927
** Description
WHAT ARE THE ODDS YOU'LL WIN THE LOTTERY?   How long will your kids wait in line at Disney World?  Who decides that "standardized tests" are fair?  Why do highway engineers build slow-moving ramps?  What does it mean, statistically, to be an "Average Joe"?  NUMBERS RULE YOUR WORLD  In the popular tradition of eye-opening bestsellers like Freakonomics, The Tipping Point, and Super Crunchers, this fascinating book from renow

* Of Human Bondage
** W. Somerset Maugham
** Rating: 4.12 / 39228
** Description
The first and most autobiographical of Maugham's masterpieces. It is the story of Philip Carey, an orphan eager for life, love and adventure. After a few months studying in Heidelberg, and a brief spell in Paris as a would-be artist, he settles in London to train as a doctor where he meets Mildred, the loud but irresistible waitress with whom he plunges into a tortured and masochistic affair.

* Of Mice and Men
** John Steinbeck
** Rating: 3.84 / 1551035
** Description
The compelling story of two outsiders striving to find their place in an unforgiving world. Drifters in search of work, George and his simple-minded friend Lennie have nothing in the world except each other and a dream--a dream that one day they will have some land of their own. Eventually they find work on a ranch in California’s Salinas Valley, but their hopes are doomed as Lennie, struggling against extreme cruelty, misunderstanding and feelings of jealousy, becomes a victim of his own streng

* Oil: A Beginner's Guide
** Vaclav Smil
** Rating: 3.66 / 186
** Description
Packed with fascinating facts and insight, this book will fuel dinner party debate, and provide readers with the science and politics behind the world’s most controversial resource. Without oil, there would be no globalisation, no plastic, little transport, and a global political landscape that few would recognise. It is the lifeblood of the modern world, and humanity’s dependence upon it looks set to continue for decades to come. In this captivating book, the author of the acclaimed Energy: A B

* On Writing Well: The Classic Guide to Writing Nonfiction
** William Zinsser
** Rating: 4.24 / 16767
** Description
On Writing Well has been praised for its sound advice, its clarity and the warmth of its style. It is a book for everybody who wants to learn how to write or who needs to do some writing to get through the day, as almost everybody does in the age of e-mail and the Internet. Whether you want to write about people or places, science and technology, business, sports, the arts or about yourself in the increasingly popular memoir genre, On Writing Well offers you fundamental pricipl

* One Flew Over the Cuckoo's Nest
** Ken Kesey
** Rating: 4.19 / 522600
** Description
In this classic of the 1960s, Ken Kesey's hero is Randle Patrick McMurphy, a boisterous, brawling, fun-loving rebel who swaggers into the world of a mental hospital and takes over. A lusty, life-affirming fighter, McMurphy rallies the other patients around him by challenging the dictatorship of Nurse Ratched. He promotes gambling in the ward, smuggles in wine and women, and openly defies the rules at every turn. But this defiance, which starts as a sport, soon develops into a grim struggle, an a

* Out of Africa
** Isak Dinesen
** Rating: 3.96 / 25079
** Description
Out of Africa is Isak Dinesen's memoir of her years in Africa, from 1914 to 1931, on a four-thousand-acre coffee plantation in the hills near Nairobi. She had come to Kenya from Denmark with her husband, and when they separated she stayed on to manage the farm by herself, visited frequently by her lover, the big-game hunter Denys Finch-Hatton, for whom she would make up stories "like Scheherazade." In Africa, "I learned how to tell tales," she recalled many years later. "The natives have

* Parallel Worlds: A Journey Through Creation, Higher Dimensions, and the Future of the Cosmos
** Michio Kaku
** Rating: 4.17 / 13827
** Description
In this thrilling journey into the mysteries of our cosmos, bestselling author Michio Kaku takes us on a dizzying ride to explore black holes and time machines, multidimensional space and, most tantalizing of all, the possibility that parallel universes may lay alongside our own. Kaku skillfully guides us through the latest innovations in string theory and its latest iteration, M-theory, which posits that our universe may be just one in an endless multiverse, a singular bubble floating in a sea

* Parallel Worlds: A Journey Through Creation, Higher Dimensions, and the Future of the Cosmos
** Michio Kaku
** Rating: 4.17 / 13827
** Description
In this thrilling journey into the mysteries of our cosmos, bestselling author Michio Kaku takes us on a dizzying ride to explore black holes and time machines, multidimensional space and, most tantalizing of all, the possibility that parallel universes may lay alongside our own. Kaku skillfully guides us through the latest innovations in string theory and its latest iteration, M-theory, which posits that our universe may be just one in an endless multiverse, a singular bubble floating in a sea

* Peopleware: Productive Projects and Teams
** Tom DeMarco
** Rating: 4.15 / 6001
** Description
Two of the computer industry's most popular authors and lecturers return with a new edition of the software management book that started a revolution.With humor and wisdom drawn from years of management and consulting experience, DeMarco and Lister demonstrate that the major issues of software development are human, not technical -- and that managers ignore them at their peril.  Now, with a new preface and eight new chapters -- expanding the original edition by one third -- the authors

* Permission Marketing: Turning Strangers Into Friends And Friends Into Customers
** Seth Godin
** Rating: 3.94 / 10679
** Description
The man Business Week calls "the ultimate entrepreneur for the Information Age" explains "Permission Marketing"—the groundbreaking concept that enables marketers to shape their message so that consumers will willingly accept it.  Whether it is the TV commercial that breaks into our favorite program, or the telemarketing phone call that disrupts a family dinner, traditional advertising is based on the hope of snatching our attention away from whatever we are doing. Seth Godin cal

* Personal Development for Smart People: The Conscious Pursuit of Personal Growth
** Steve Pavlina
** Rating: 3.94 / 3510
** Description
Despite promises of “fast and easy” results from slick marketers, real personal growth is neither fast nor easy. The truth is that hard work, courage, and self-discipline are required to achieve meaningful results—results that are not attained by those who cling to the fantasy of achievement without effort.         Personal Development for Smart People reveals the unvarnished truth about what it takes to consciously grow as a human being. As you read, you’ll l

* Pitch Anything: An Innovative Method for Presenting, Persuading, and Winning the Deal
** Oren Klaff
** Rating: 4.09 / 4967
** Description
About the Book:  When it comes to delivering a pitch, Oren Klaff has unparalleled credentials. Over the past 13 years, he has used his one-of-a- kind method to raise more than $400 million--and now, for the fi rst time, he describes his formula to help you deliver a winning pitch in any business situation.  Whether you're selling ideas to investors, pitching a client for new business, or even negotiating for a higher salary, "Pitch Anything "will transform the way you positio

* Pomodoro Technique Illustrated
** Staffan Noteberg
** Rating: 3.76 / 787
** Description
Do you ever look at the clock and wonder where the day went? You spent all this time at work and didn't come close to getting everything done. Tomorrow try something new. Use the Pomodoro Technique to work in focused sprints throughout the day. In Pomodoro Technique Illustrated, Staffan N teberg shows you how to organize your work to accomplish more in less time. There's no need for expensive software or fancy planners. You can get started with nothing more than a piece of paper, a pencil

* Portnoy's Complaint
** Philip Roth
** Rating: 3.70 / 43247
** Description
The famous confession of Alexander Portnoy, who is thrust through life by his unappeasable sexuality, yet held back at the same time by the iron grip of his unforgettable childhood. Hilariously funny, boldly intimate, startlingly candid, Portnoy’s Complaint was an immediate bestseller upon its publication in 1969, and is perhaps Roth’s best-known book.  Portnoy's Complaint n. [after Alexander Portnoy (1933-)] A disorder in which strongly-felt ethical and altruistic impuls

* Power: Why Some People Have it and Others Don't
** Jeffrey Pfeffer
** Rating: 3.86 / 1895
** Description
“Pfeffer [blends] academic rigor and practical genius into wonderfully readable text. The leading thinker on the topic of power, Pfeffer here distills his wisdom into an indispensable guide.” —Jim Collins, author of New York Times bestselling author Good to Great and How the Mighty Fall     Some people have it, and others don’t—Jeffrey Pfeffer explores why in Power. One of the greatest minds in management theory and author or co-author

* Preacher, Volume 1: Gone to Texas
** Garth Ennis
** Rating: 4.16 / 53663
** Description
One of the most celebrated comics titles of the late 1990s, PREACHER is a modern American epic of life, death, love and redemption also packed with sex, booze, blood and bullets - not to mention angels, demons, God, vampires and deviants of all stripes.  At first glance, the Reverend Jesse Custer doesn't look like anyone special-just another small-town minister slowly losing his flock and his faith. But he's about to come face-to-face with proof that God does indeed exist. Merging with

* Presentation Zen: Simple Ideas on Presentation Design and Delivery
** Garr Reynolds
** Rating: 4.08 / 11760
** Description
Best-selling author and popular speaker Garr Reynolds is back in this newly revised edition of his classic, best-selling book,  Presentation Zen,  in which he showed readers there is a better way to reach the audience through simplicity and storytelling, and gave them the tools to confidently design and deliver successful presentations.  In this new edition, Garr gives his readers new, fresh examples to draw inspiration from, with a whole new chapter for those who present on mor

* Product Strategy for High Technology Companies
** Michael E. McGrath
** Rating: 3.62 / 108
** Description
One of the key determinants of success for today's high-technology companies is product strategy--and this guide continues to be the only book on product strategy written specifically for the 21st century high-tech industry. More than 250 examples from technological leaders including IBM, Compaq, and Apple--plus a new focus on growth strategies and on Internet businesses--define how high-tech companies can use product strategy and product platform strategy for competitiveness, profitability, and

* Professional Node.Js: Building JavaScript Based Scalable Software
** Pedro Teixeira
** Rating: 3.79 / 87
** Description
Learn to build fast and scalable software in JavaScript with Node.js Node.js is a powerful and popular new framework for writing scalable network programs using JavaScript. This no nonsense book begins with an overview of Node.js and then quickly dives into the code, core concepts, and APIs. In-depth coverage pares down the essentials to cover debugging, unit testing, and flow control so that you can start building and testing your own modules right away.   Covers node and

* Programming Pearls
** Jon L. Bentley
** Rating: 4.21 / 2483
** Description
The first edition of Programming Pearls was one of the most influential books I read early in my career, and many of the insights I first encountered in that book stayed with me long after I read it. Jon has done a wonderful job of updating the material. I am very impressed at how fresh the new examples seem. - Steve McConnell When programmers list their favorite books, Jon Bentley's collection of programming pearls is commonly included among the classics. Just as natural pearls grow from grains

* Rapid Development: Taming Wild Software Schedules
** Steve McConnell
** Rating: 3.95 / 1094
** Description
A fundamental software engineering project management guide based on the practical requirements of "Taming Wild Software Schedules". Emphasizes possible, realistic and "best practice" approaches for managers, technical leads and self-managed teams. The author emphasizes efficient development concepts with an examination of rapid development strategies and a study of classic mistakes, within the context of software-development fundamentals and risk management. Dissects the core issues of rapid de

* Ready for Anything: 52 Productivity Principles for Work and Life
** David    Allen
** Rating: 3.80 / 3373
** Description

* Refactoring: Improving the Design of Existing Code
** Martin Fowler
** Rating: 4.21 / 5187
** Description
As the application of object technology—particularly the Java programming language—has become commonplace, a new problem has emerged to confront the software development community. Significant numbers of poorly designed programs have been created by less-experienced developers, resulting in applications that are inefficient and hard to maintain and extend. Increasingly, software system professionals are discovering just how difficult it is to work with these inherited, non-optimal applications.

* Release It!: Design and Deploy Production-Ready Software
** Michael T. Nygard
** Rating: 4.18 / 1575
** Description
Whether it's in Java, .NET, or Ruby on Rails, getting your application ready to ship is only half the battle. Did you design your system to survivef a sudden rush of visitors from Digg or Slashdot? Or an influx of real world customers from 100 different countries? Are you ready for a world filled with flakey networks, tangled databases, and impatient users?  If you're a developer and don't want to be on call for 3AM for the rest of your life, this book will help.different kind of business book - one that explores a new reality. Today, anyone can be in business. Tools that used to be out of reach are now easily accessible. Technology that cost thousands is now just a few pounds or even free. Stuff that was impossible just a few years ago is now simple.  That means anyone can start a business. And you can do it without working miserable 80-hour weeks or depleting

* Selected Stories
** Alice Munro
** Rating: 4.30 / 5515
** Description
Spanning almost thirty years and settings that range from big cities to small towns and farmsteads of rural Canada, this magnificent collection brings together twenty-eight stories by a writer of unparalleled wit, generosity, and emotional power. In her Selected Stories, Alice Munro makes lives that seem small unfold until they are revealed to be as spacious as prairies and locates the moments of love and betrayal, desire and forgiveness, that change those lives forever. To read these sto

* Sense and Sensibility
** Jane Austen
** Rating: 4.06 / 786587
** Description
'The more I know of the world, the more am I convinced that I shall never see a man whom I can really love. I require so much!'  Marianne Dashwood wears her heart on her sleeve, and when she falls in love with the dashing but unsuitable John Willoughby she ignores her sister Elinor's warning that her impulsive behaviour leaves her open to gossip and innuendo. Meanwhile Elinor, always sensitive to social convention, is struggling to conceal her own romantic disappointment, even f

* Shōgun (Asian Saga, #1)
** James Clavell
** Rating: 4.37 / 118127
** Description
Librarian's note: An alternate cover edition can be found here  A bold English adventurer. An invincible Japanese warlord. A beautiful woman torn between two ways of life, two ways of love. All brought together in an extraordinary saga of a time and a place aflame with conflict, passion, ambition, lust, and the struggle for power...

* Siddhartha
** Hermann Hesse
** Rating: 3.99 / 430526
** Description
Siddhartha   Este libro electrónico tiene una mesa activa de los contenidos  Siddhartha es una novela de Hermann Hesse, que se ocupa del viaje espiritual de unniño conocido como Siddhartha del subcontinente indio durante el tiempo del Buda. El libro, novena novela de Hesse, fue escrita en alemán, en un estilo sencillo peropotente y lírica. Se publicó en los EE.UU. en 1951 y se convirtió en influyente durante ladécada de 1960. Hesse Siddharta dedicada a Ninon Hesse, su es

* Silent Spring
** Rachel Carson
** Rating: 3.94 / 25933
** Description
Rachel Carson’s Silent Spring was first published in three serialized excerpts in the New Yorker in June of 1962. The book appeared in September of that year and the outcry that followed its publication forced the banning of DDT and spurred revolutionary changes in the laws affecting our air, land, and water. Carson’s passionate concern for the future of our planet reverberated powerfully throughout the world, and her eloquent book was instrumental in launching the environmental movement. It is

* Snow Crash
** Neal Stephenson
** Rating: 4.02 / 191253
** Description
In reality, Hiro Protagonist delivers pizza for Uncle Enzo’s CosoNostra Pizza Inc., but in the Metaverse he’s a warrior prince. Plunging headlong into the enigma of a new computer virus that’s striking down hackers everywhere, he races along the neon-lit streets on a search-and-destroy mission for the shadowy virtual villain threatening to bring about infocalypse. Snow Crash is a mind-altering romp through a future America so bizarre, so outrageous…you’ll recognize it immediately.

* So Good They Can't Ignore You: Why Skills Trump Passion in the Quest for Work You Love
** Cal Newport
** Rating: 4.09 / 11865
** Description
In this eye-opening account, Cal Newport debunks the long-held belief that "follow your passion" is good advice.   Not only is the cliché flawed-preexisting passions are rare and have little to do with how most people end up loving their work-but it can also be dangerous, leading to anxiety and chronic job hopping.  After making his case against passion, Newport sets out on a quest to discover the reality of how people end up loving what they do. Spending time with organic farmers, ven

* Software Estimation: Demystifying the Black Art
** Steve McConnell
** Rating: 4.00 / 681
** Description
Often referred to as the "black art" because of its complexity and uncertainty, software estimation is not as difficult or puzzling as people think. In fact, generating accurate estimates is straightforward--once you understand the art of creating them. In his highly anticipated book, acclaimed author Steve McConnell unravels the mystery to successful software estimation--distilling academic information and real-world experience into a practical guide for working software professionals. Instead

* Start with Why: How Great Leaders Inspire Everyone to Take Action
** Simon Sinek
** Rating: 4.07 / 40880
** Description
Why do you do what you do?   Why are some people and organizations more innovative, more influential, and more profitable than others? Why do some command greater loyalty from customers and employees alike? Even among the successful, why are so few able to repeat their success over and over?    People like Martin Luther King Jr., Steve Jobs, and the Wright Brothers might have little in common, but they all started with why. It was their natural ability to start

* Steal Like an Artist: 10 Things Nobody Told You About Being Creative
** Austin Kleon
** Rating: 3.86 / 107724
** Description
You don’t need to be a genius, you just need to be yourself. That’s the message from Austin Kleon, a young writer and artist who knows that creativity is everywhere, creativity is for everyone. A manifesto for the digital age, Steal Like an Artist is a guide whose positive message, graphic look and illustrations, exercises, and examples will put readers directly in touch with their artistic side.

* Stumbling on Happiness
** Daniel Todd Gilbert
** Rating: 3.82 / 41120
** Description
• Why are lovers quicker to forgive their partners for infidelity than for leaving dirty dishes in the sink? • Why will sighted people pay more to avoid going blind than blind people will pay to regain their sight? • Why do dining companions insist on ordering different meals instead of getting what they really want? • Why do pigeons seem to have such excellent aim; why can’t we remember one song while listening to another; and why does the line at the grocery store always slow down the moment w

* Talent is Overrated: What Really Separates World-Class Performers from Everybody Else
** Geoff Colvin
** Rating: 3.97 / 13796
** Description
Expanding on a landmark cover story in Fortune, a top journalist debunks the myths of exceptional performance.  One of the most popular Fortune articles in many years was a cover story called: "What It Takes to Be Great." Geoff Colvin offered new evidence that top performers in any field -- from Tiger Woods and Winston Churchill to Warren Buffett and Jack Welch -- are not determined by their inborn talents. Greatness doesn't come from DNA but from practice and pers

* Team of Rivals: The Political Genius of Abraham Lincoln
** Doris Kearns Goodwin
** Rating: 4.29 / 111645
** Description
The life and times of Abraham Lincoln have been analyzed and dissected in countless books. Do we need another Lincoln biography? In Team of Rivals, esteemed historian Doris Kearns Goodwin proves that we do. Though she can't help but cover some familiar territory, her perspective is focused enough to offer fresh insights into Lincoln's leadership style and his deep understanding of human behavior and motivation. Goodwin makes the case for Lincoln's political genius by examining his relatio

* The 4-Hour Workweek
** Timothy Ferriss
** Rating: 3.84 / 83596
** Description
What do you do? Tim Ferriss has trouble answering the question. Depending on when you ask this controversial Princeton University guest lecturer, he might answer: "I race motorcycles in Europe." "I ski in the Andes." "I scuba dive in Panama." "I dance tango in Buenos Aires." He has spent more than five years learning the secrets of the New Rich, a fast-growing subculture who has abandoned the "deferred-life plan" and instead mastered the new currencies-time and mobility-to create luxury lifestyl

* The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change
** Stephen R. Covey
** Rating: 4.05 / 351714
** Description
In The 7 Habits of Highly Effective People, author Stephen R. Covey presents a holistic, integrated, principle-centered approach for solving personal and professional problems. With penetrating insights and pointed anecdotes, Covey reveals a step-by-step pathway for living with fairness, integrity, service, and human dignity -- principles that give us the security to adapt to change and the wisdom and power to take advantage of the opportunities that change creates.

* The 80/20 Principle: The Secret to Achieving More with Less
** Richard Koch
** Rating: 4.00 / 14110
** Description
How anyone can be more effective with less effort by learning how to identify and leverage the 80/20 principle--the well-known, unpublicized secret that 80 percent of all our results in business and in life stem from a mere 20 percent of our efforts.  The 80/20 principle is one of the great secrets of highly effective people and organizations.  Did you know, for example, that 20 percent of customers account for 80 percent of revenues? That 20 percent of our time accounts for

* The Adventures of Tom Sawyer
** Mark Twain
** Rating: 3.90 / 605376
** Description
The Adventures of Tom Sawyer is the first of Mark Twain's novels to feature one of the best-loved characters in American fiction, with a critical introduction by John Seelye in Penguin Classics. From the famous episodes of the whitewashed fence and the ordeal in the cave to the trial of Injun Joe, The Adventures of Tom Sawyer is redolent of life in the Mississippi River towns in which Twain spent his own youth. A sombre undercurrent flows through the high humour and unabashed nosta

* The Age of Innocence
** Edith Wharton
** Rating: 3.93 / 117077
** Description
Winner of the 1921 Pulitzer Prize, The Age of Innocence is Edith Wharton’s masterful portrait of desire and betrayal during the sumptuous Golden Age of Old New York, a time when society people “dreaded scandal more than disease.”  This is Newland Archer’s world as he prepares to marry the beautiful but conventional May Welland. But when the mysterious Countess Ellen Olenska returns to New York after a disastrous marriage, Archer falls deeply in love with her. Torn between

* The Aleph and Other Stories
** Jorge Luis Borges
** Rating: 4.39 / 23307
** Description
Full of philosophical puzzles and supernatural surprises, these stories contain some of Borges’s most fully realized human characters. With uncanny insight he takes us inside the minds of an unrepentant Nazi, an imprisoned Mayan priest, fanatical Christian theologians, a woman plotting vengeance on her father’s “killer,” and a man awaiting his assassin in a Buenos Aires guest house.  This volume also contains the hauntingly brief vignettes about literary imagination and personal identity collect

* The Amazing Adventures of Kavalier & Clay
** Michael Chabon
** Rating: 4.17 / 159277
** Description
Joe Kavalier, a young Jewish artist who has also been trained in the art of Houdini-esque escape, has just smuggled himself out of Nazi-invaded Prague and landed in New York City. His Brooklyn cousin Sammy Clay is looking for a partner to create heroes, stories, and art for the latest novelty to hit America - the comic book. Drawing on their own fears and dreams, Kavalier and Clay create the Escapist, the Monitor, and Luna Moth, inspired by the beautiful Rosa Saks, who will become linked by powe

* The Art of Being Unmistakable
** Srinivas Rao
** Rating: 3.77 / 478
** Description
We live in such a hyper-connected society today flooded with so much talent and so much noise. Talent alone won’t cut it. Whether you’re an artist, musician, writer or creator of sorts, to stand out in the world you must be unmistakable.    It’s the only option.   To create unmistakable work, you must take risks. You must cross lines, personal and professional. You must go to the point of a no return. On my 34th birthday, I asked myself a question. "If this had been the

* The Art of Possibility
** Rosamund Stone Zander
** Rating: 4.05 / 4817
** Description
Presenting twelve breakthrough practices for bringing creativity into all human endeavors, The Art of Possibility is the dynamic product of an extraordinary partnership. The Art of Possibility combines Benjamin Zander's experience as conductor of the Boston Philharmonic and his talent as a teacher and communicator with psychotherapist Rosamund Stone Zander's genius for designing innovative paradigms for personal and professional fulfillment.  The authors' harmoniously interwoven perspective

* The Art of Project Management
** Scott Berkun
** Rating: 3.91 / 646
** Description
The Art of Project Management covers it all--from practical methods for making sure work gets done right and on time, to the mindset that can make you a great leader motivating your team to do their best. Reading this was like reading the blueprint for how the best projects are managed at Microsoft... I wish we always put these lessons into action!" --Joe Belfiore, General Manager, E-home Division, Microsoft Corporation   "Berkun has written a fast paced, jargon-free and witty guide to

* The Art of Thinking Clearly
** Rolf Dobelli
** Rating: 3.80 / 11941
** Description
In engaging prose and with practical examples and anecdotes, an eye-opening look at human reasoning and essential reading for anyone with important decisions to make.  Have you ever: • Invested time in something that, with hindsight, just wasn't worth it? • Overpayed in an Ebay auction? • Continued doing something you knew was bad for you? • Sold stocks too late, or too early? • Taken credit for success, but blamed failure on external circumstances? • Back

* The Art of Travel
** Alain de Botton
** Rating: 3.81 / 15363
** Description
Any Baedeker will tell us where we ought to travel, but only Alain de Botton will tell us how and why. With the same intelligence and insouciant charm he brought to How Proust Can Save Your Life, de Botton considers the pleasures of anticipation; the allure of the exotic, and the value of noticing everything from a seascape in Barbados to the takeoffs at Heathrow.   Even as de Botton takes the reader along on his own peregrinations, he also cites such

* The Autobiography of Malcolm X
** Malcolm X
** Rating: 4.29 / 138551
** Description
If there was one man who articulated the anger, the struggle, and the beliefs of African Americans in the 1960s, that man was Malcolm X. His Autobiography is now an established classic of modern America, a book that expresses like none other the crucial truth about our violent times.

* The Bad Beginning (A Series of Unfortunate Events, #1)
** Lemony Snicket
** Rating: 3.90 / 302215
** Description
Dear Reader,  I'm sorry to say that the book you are holding in your hands is extremely unpleasant. It tells an unhappy tale about three very unlucky children. Even though they are charming and clever, the Baudelaire siblings lead lives filled with misery and woe. From the very first page of this book when the children are at the beach and receive terrible news, continuing on through the entire story, disaster lurks at their heels. One might say they are magnets for misfortune. Selected by The New York Times Book Review as a Notable Book of the Year.  The author of The New York Times bestseller The Stuff of Thought offers a controversial history of violence.   Faced with the ceaseless stream of news about war, crime, and terrorism, one could easily think we live in the most violent age ever seen. Yet as New York Times bestselling author Steven Pinker shows in this startling and engaging new work, just the opposite is true: v

* The Big Moo: Stop Trying to Be Perfect and Start Being Remarkable
** The Group of 33
** Rating: 3.79 / 2283
** Description
How do you create a big moo-an insight so astounding that people can't help but remark on it, like digital TV recording (TiVo) or overnight shipping (FedEx), or the world's best vacuum cleaner (Dyson)? Seth Godin worked with thirty-two of the world's smartest thinkers to answer this critical question. And the team-with the likes of Tom Peters, Malcolm Gladwell, Guy Kawasaki, Mark Cuban, Robyn Waters, Dave Balter, Red Maxwell, and Randall Rothenberg on board- created an incredibly useful book tha

* The Big Short: Inside the Doomsday Machine
** Michael   Lewis
** Rating: 4.26 / 102463
** Description
The real story of the crash began in bizarre feeder markets where the sun doesn't shine and the SEC doesn't dare, or bother, to tread: the bond and real estate derivative markets where geeks invent impenetrable securities to profit from the misery of lower- and middle-class Americans who can't pay their debts. The smart people who understood what was or might be happening were paralyzed by hope and fear; in any case, they weren't talking.  Michael Lewis creates a fresh, character-drive

* The Birth of Tragedy
** Friedrich Nietzsche
** Rating: 3.98 / 9741
** Description
A compelling argument for the necessity for art in life, Nietzsche's first book is fuelled by his enthusiasms for Greek tragedy, for the philosophy of Schopenhauer and for the music of Wagner, to whom this work was dedicated. Nietzsche outlined a distinction between its two central forces: the Apolline, representing beauty and order, and the Dionysiac, a primal or ecstatic reaction to the sublime. He believed the combination of these states produced the highest forms of music and tragic drama, w

* The Black Swan: The Impact of the Highly Improbable
** Nassim Nicholas Taleb
** Rating: 3.89 / 60247
** Description
A black swan is a highly improbable event with three principal characteristics: It is unpredictable; it carries a massive impact; and, after the fact, we concoct an explanation that makes it appear less random, and more predictable, than it was.   The astonishing success of Google was a black swan; so was 9/11. For Nassim Nicholas Taleb, black swans underlie almost everything about our world, from the rise of religions to events in our own personal lives.  Why do we not ackno

* DONE The Book on the Taboo Against Knowing Who You Are
  CLOSED: [2017-11-24 Fri 16:07]
** Alan W. Watts
** Rating: 4.28 / 10956
** Description
At the root of human conflict is our fundamental misunderstanding of who we are. The illusion that we are isolated beings, unconnected to the rest of the universe, has led us to view the “outside” world with hostility, and has fueled our misuse of technology and our violent and hostile subjugation of the natural world. In The Book, philosopher Alan Watts provides us with a much-needed answer to the problem of personal identity, distilling and adapting the ancient Hindu philosophy of Vedan

* The Box: How the Shipping Container Made the World Smaller and the World Economy Bigger
** Marc Levinson
** Rating: 3.87 / 2647
** Description
In April 1956, a refitted oil tanker carried fifty-eight shipping containers from Newark to Houston. From that modest beginning, container shipping developed into a huge industry that made the boom in global trade possible. "The Box" tells the dramatic story of the container's creation, the decade of struggle before it was widely adopted, and the sweeping economic consequences of the sharp fall in transportation costs that containerization brought about.  Published on the fiftieth anni

* The Brief Wondrous Life of Oscar Wao
** Junot Díaz
** Rating: 3.89 / 185259
** Description
Things have never been easy for Oscar, a sweet but disastrously overweight, lovesick Dominican ghetto nerd. From his home in New Jersey, where he lives with his old-world mother and rebellious sister, Oscar dreams of becoming the Dominican J. R. R. Tolkien and, most of all, of finding love. But he may never get what he wants, thanks to the Fukœ-the curse that has haunted the Oscar's family for generations, dooming them to prison, torture, tragic accidents, and, above all, ill-starred love. Oscar

* The Bully Pulpit: Theodore Roosevelt, William Howard Taft, and the Golden Age of Journalism
** Doris Kearns Goodwin
** Rating: 4.16 / 12447
** Description
Doris Kearns Goodwin, winner of the Pulitzer Prize and author of Team of Rivals, captures the Progressive Era through the story of the broken friendship between Theodore Roosevelt and William Howard Taft, culminating in their running against one another for president in 1912.

* The Call of the Wild
** Jack London
** Rating: 3.83 / 254650
** Description
A classic novel reissued for contemporary readers.  Rediscover Jack London’s beloved classic in this unique hardbound edition. First published as a serial in the Saturday Evening Post in 1903, The Call of the Wild has never been out of print.  Follow a dog named Buck through violence and hardship, loyalty and loss, finally finding himself and his home in the Yukon wilderness. Truly a must-have for London fans, book lovers, and adventurers.

* The Catcher in the Rye
** J.D. Salinger
** Rating: 3.79 / 2169957
** Description
The hero-narrator of The Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caulfield. Through circumstances that tend to preclude adult, secondhand description, he leaves his prep school in Pennsylvania and goes underground in New York City for three days. The boy himself is at once too simple and too complex for us to make any final comment about him or his story. Perhaps the safest thing we can say about Holden is that he was born in the world not just

* The Checklist Manifesto: How to Get Things Right
** Atul Gawande
** Rating: 4.03 / 29439
** Description
The New York Times bestselling author of Better and Complications reveals the surprising power of the ordinary checklist We live in a world of great and increasing complexity, where even the most expert professionals struggle to master the tasks they face. Longer training, ever more advanced technologies‚neither seems to prevent grievous errors. But in a hopeful turn, acclaimed surgeon and writer Atul Gawande finds a remedy in the humblest and simplest of te

* The Color of Water: A Black Man's Tribute to His White Mother
** James McBride
** Rating: 4.06 / 85305
** Description
Touches readers of all colors as a vivid portrait of growing up, a haunting meditation on race and identity, and a lyrical valentine to a mother from her son.  Who is Ruth McBride Jordan? A self-declared "light-skinned" woman evasive about her ethnicity, yet steadfast in her love for her twelve black children. James McBride, journalist, musician and son, explores his mother's past, as well as his own upbringing and heritage, in a poignant and powerful debut, The Color Of Water: A Black

* The Complete Sherlock Holmes
** Arthur Conan Doyle
** Rating: 4.50 / 129152
** Description
Ever since he made his first appearance in A Study In Scarlet, Sherlock Holmes has enthralled and delighted millions of fans throughout the world.

* The Complete Works
** William Shakespeare
** Rating: 4.49 / 46470
** Description
The tempest -- Two gentlemen of Verona -- Merry wives of Windsor -- Twelfth night, or, What you will -- Measure for measure -- Much ado about nothing -- A midsummer night's dream -- Love's labour's lost -- The merchant of Venice -- As you like it -- All's well that ends well -- The taming of the shrew -- The winter's tale -- The comedy of errors -- King John -- The life and death of King Richard II -- King Henry IV [

* The Corrections
** Jonathan Franzen
** Rating: 3.78 / 133714
** Description
The Lamberts – Enid and Alfred and their three grown-up children – are a troubled family living in a troubled age. Alfred is ill and as his condition worsens the whole family must face the failures, secrets and long-buried hurts that haunt them if they are to make the corrections that each desperately needs. Stretching from the Midwest in the mid-century to Wall Street and Eastern Europe in the age of globalised greed, The Corrections brings an old-time America of freight trains and civic duty i

* The Dark Tower (The Dark Tower, #7)
** Stephen King
** Rating: 4.27 / 108578
** Description
The seventh and final installment of Stephen King's The Dark Tower saga is perhaps the most anticipated book in the author's long career. King began this epic tale about the last gunslinger in the world more than 20 years ago; now he draws its suspenseful story to a close, snapping together the last pieces of his action puzzle and drawing Roland Deschain ever closer to his ultimate goal.

* The Death of Ivan Ilych And Other Stories
** Leo Tolstoy
** Rating: 4.08 / 9921
** Description
Leo Tolstoy combined detailed physical description with perceptive psychological insight to sweep aside the sham of surface appearances and lay bare man's intimate gestures, acts, and thoughts. Murder and sacrifice... greed and devotion... lust and affection... vanity and love -- one by one, in this volume of great stories, Tolstoy dissects the basic drives, emotions, and motives of ordinary people searching for self-knowledge and spiritual perfection. Chekhov said, "Of authors my favorite is To

* The Design of Everyday Things
** Donald A. Norman
** Rating: 4.18 / 15966
** Description
Anyone who designs anything to be used by humans -- from physical objects to computer programs to conceptual tools -- must read this book, and it is an equally tremendous read for anyone who has to use anything created by another human. It could forever change how you experience and interact with your physical surroundings, open your eyes to the perversity of bad design and the desirability of good design, and raise your expectations about how things should be designed.  B &amp;

* The Devil in the White City: Murder, Magic, and Madness at the Fair That Changed America
** Erik Larson
** Rating: 3.99 / 359054
** Description
Erik Larson's gifts as a storyteller are magnificently displayed in this rich narrative of the master builder, the killer, and the great fair that obsessed them both.  Two men, each handsome and unusually adept at his chosen work, embodied an element of the great dynamic that characterized America's rush toward the twentieth century. The architect was Daniel Hudson Burnham, the fair's brilliant director of works and the builder of many of the country's most important structures, includ

* The Diary of a Young Girl
** Anne Frank
** Rating: 4.10 / 2085806
** Description
Discovered in the attic in which she spent the last years of her life, Anne Frank's remarkable diary has since become a world classic—a powerful reminder of the horrors of war and an eloquent testament to the human spirit.  In 1942, with Nazis occupying Holland, a thirteen-year-old Jewish girl and her family fled their home in Amsterdam and went into hiding. For the next two years, until their whereabouts were betrayed to the Gestapo, they and another family lived cloistered in the "Se

* The Dip: A Little Book That Teaches You When to Quit
** Seth Godin
** Rating: 3.83 / 16646
** Description
The old saying is wrong—winners do quit, and quitters do win.    Every new project (or job, or hobby, or company) starts out exciting and fun. Then it gets harder and less fun, until it hits a low point—really hard, and not much fun at all.    And then you find yourself asking if the goal is even worth the hassle. Maybe you're in a Dip—a temporary setback that will get better if you keep pushing. But maybe it's really a Cul-de-Sac, which will never get better, no matter how h

* The Drunkard's Walk: How Randomness Rules Our Lives
** Leonard Mlodinow
** Rating: 3.88 / 15370
** Description
In this irreverent and illuminating book, acclaimed writer and scientist Leonard Mlodinow shows us how randomness, change, and probability reveal a tremendous amount about our daily lives, and how we misunderstand the significance of everything from a casual conversation to a major financial setback. As a result, successes and failures in life are often attributed to clear and obvious cases, when in actuality they are more profoundly influenced by chance.  The rise and fall of your fav

* The E-Myth Revisited: Why Most Small Businesses Don't Work and What to Do About It
** Michael E. Gerber
** Rating: 3.98 / 40359
** Description
E-Myth \ 'e-,'mith\ n 1: the entrepreneurial myth: the myth that most people who start small businesses are entrepreneurs 2: the fatal assumption that an individual who understands the technical work of a business can successfully run a business that does that technical work  Voted #1 business book by Inc. 500 CEOs.  An instant classic, this revised and updated edition of the phenomenal bestseller dispels the myths about starting your own business. Small business con

* The Elegant Universe: Superstrings, Hidden Dimensions, and the Quest for the Ultimate Theory
** Brian Greene
** Rating: 4.06 / 71538
** Description
In a rare blend of scientific insight and writing as elegant as the theories it explains, Brian Greene, one of the world's leading string theorists, peels away the layers of mystery surrounding string theory to reveal a universe that consists of eleven dimensions, where the fabric of space tears and repairs itself, and all matter—from the smallest quarks to the most gargantuan supernovas—is generated by the vibrations of microscopically tiny loops of energy.  Greene uses examples rangi

* The Elements of Style
** William Strunk Jr.
** Rating: 4.20 / 58776
** Description
This style manual offers practical advice on improving writing skills. Throughout, the emphasis is on promoting a plain English style. This little book can help you communicate more effectively by showing you how to enliven your sentences.

* The Entrepreneur's Guide to Customer Development: A "Cheat Sheet" to the Four Steps to the Epiphany
** Brant Cooper
** Rating: 4.01 / 2404
** Description

* The Fault in Our Stars
** John Green
** Rating: 4.26 / 2570347
** Description
There is an alternate cover edition here.  "I fell in love the way you fall asleep: slowly, then all at once."  Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a gorgeous plot twist named Augustus Waters suddenly appears at Cancer Kid Support Group,

* The Fellowship of the Ring (The Lord of the Rings, #1)
** J.R.R. Tolkien
** Rating: 4.34 / 1883039
** Description
One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkeness bind them  In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, The Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit. What you are today is not important... for in this  runaway bestseller you will learn how to change your life by applying the secrets you are about to  discover in the ancient scrolls.Our most commonly held formula for success is broken.   Conventional wisdom holds that if we work hard we will be more successful, and if we are more successful, then we’ll be happy. If we can just find that great job, win that next promotion, lose those five pounds, happiness will follow. But recent discoveries in the field of positive psychology have shown that this formula is actually backward: Happiness fuels success, not the other way around. When we ar

* The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy, #1)
** Douglas Adams
** Rating: 4.20 / 1027680
** Description
Seconds before the Earth is demolished to make way for a galactic freeway, Arthur Dent is plucked off the planet by his friend Ford Prefect, a researcher for the revised edition of The Hitchhiker's Guide to the Galaxy who, for the last fifteen years, has been posing as an out-of-work actor.  Together this dynamic pair begin a journey through space aided by quotes from The Hitchhiker's Guide ("A towel is about the most massively useful thing an interstellar hitchhiker can have") and a g

* The Hot Zone: The Terrifying True Story of the Origins of the Ebola Virus
** Richard   Preston
** Rating: 4.10 / 78033
** Description
The bestselling landmark account of the first emergence of the Ebola virus. A highly infectious, deadly virus from the central African rain forest suddenly appears in the suburbs of Washington, D.C. There is no cure. In a few days 90 percent of its victims are dead. A secret military SWAT team of soldiers and scientists is mobilized to stop the outbreak of this exotic "hot" virus. The Hot Zone tells this dramatic story, giving a hair-raising account of the appearance of rare and le

* The House at Pooh Corner (Winnie-the-Pooh, #2)
** A.A. Milne
** Rating: 4.36 / 72050
** Description
This deluxe edition of The House At Pooh Corner is the perfect way to celebrate the enduring popularity of A. A. Milne’s classic work and a stunning companion to the Winnie-the-Pooh 80th Anniversary Edition. The interior features the unabridged text and Ernest H. Shepard’s charming illustrations in full color on cream-colored stock. It is an impressive package for new fans and collectors both. Three cheers for Pooh!

* The Idiot
** Fyodor Dostoyevsky
** Rating: 4.18 / 94238
** Description
Returning to Russia from a sanitarium in Switzerland, the Christ-like epileptic Prince Myshkin finds himself enmeshed in a tangle of love, torn between two women—the notorious kept woman Nastasya and the pure Aglaia—both involved, in turn, with the corrupt, money-hungry Ganya. In the end, Myshkin’s honesty, goodness, and integrity are shown to be unequal to the moral emptiness of those around him. In her revision of the Garnett translation, Anna Brailovsky has corrected inaccuracies wrought by G

* The Immortal Life of Henrietta Lacks
** Rebecca Skloot
** Rating: 4.04 / 419584
** Description

  Intimate in feeling, astonishing in scope, and impossible to put down, The Immortal Life of Henrietta Lacks captures the beauty and drama of scientific discovery, as well as its human consequences.
Her name was Henrietta Lacks, but scientists know her as HeLa. She was a poor Southern tobacco farmer who worked the same land as her slave ancestors, yet her cells—taken without her knowledge—became one of the most important tools in medicine. The first “immortal” h

* The Innovator's DNA: Mastering the Five Skills of Disruptive Innovators
** Jeffrey H. Dyer
** Rating: 4.01 / 2150
** Description
A new classic, cited by leaders and media around the globe as a highly recommended read for anyone interested in innovation.  In The Innovator’s DNA, authors Jeffrey Dyer, Hal Gregersen, and bestselling author Clayton Christensen (The Innovator’s Dilemma, The Innovator’s Solution, How Will You Measure Your Life?) build on what we know about disruptive innovation to show how individuals can develop the skills necessary to move progressively from idea to impac

* The Innovator's Dilemma: The Revolutionary Book that Will Change the Way You Do Business
** Clayton M. Christensen
** Rating: 4.00 / 25605
** Description

* The Innovator's Solution: Creating and Sustaining Successful Growth
** Clayton M. Christensen
** Rating: 4.03 / 6896
** Description
Traditional Chinese edition of The Innovators Solution: Creating and Sustaining Successful Growth. This book teaches new businesses how to outpace the competition and sustain growth in the market by thinking outside of conventional methods. Examples from successful businesses are cited, and business-making decisions are examined.

* The Knack: How Street-Smart Entrepreneurs Learn to Handle Whatever Comes Up
** Norm Brodsky
** Rating: 3.84 / 4290
** Description
Two of Inc. magazine's hugely popular columnists show how small-business people can deal with all kinds of tricky situations.   People starting out in business tend to seek step-by-step formulas or specific rules, but in reality there are no magic bullets. Rather, says veteran entrepreneur Norm Brodsky, there's a mentality that helps street-smart people solve problems and pursue opportunities as they arise. He calls it 'the knack,' and it has made all the difference to th

* The Law
** Frédéric Bastiat
** Rating: 4.39 / 8027
** Description
How is it that the law enforcer itself does not have to keep the law? How is it that the law permits the state to lawfully engage in actions which, if undertaken by individuals, would land them in jail? These are among the most intriguing issues in political and economic philosophy. More specifically, the problem of law that itself violates law is an insurmountable conundrum of all statist philosophies. The problem has never been discussed so profoundly and passionately as in this essay by Frede

* The Liars' Club
** Mary Karr
** Rating: 3.92 / 48621
** Description
When it was published in 1995, Mary Karr's The Liars Club took the world by storm and raised the art of the memoir to an entirely new level, as well as bringing about a dramatic revival of the form. Karr's comic childhood in an east Texas oil town brings us characters as darkly hilarious as any of J. D. Salinger's—a hard-drinking daddy, a sister who can talk down the sheriff at twelve, and an oft-married mother whose accumulated secrets threaten to destroy them all. Now with a new introdu

* The Lightning Thief (Percy Jackson and the Olympians, #1)
** Rick Riordan
** Rating: 4.23 / 1461253
** Description
Alternate Cover Edition can be found here.   Percy Jackson is a good kid, but he can't seem to focus on his schoolwork or control his temper. And lately, being away at boarding school is only getting worse—Percy could have sworn his pre-algebra teacher turned into a monster and tried to kill him. When Percy's mom finds out, she knows it's time that he knew the truth about where he came from, a

* The Little Book of Contentment: A Guide to Becoming Happy with Life and Who You Are, While Getting Things Done
** Leo Babauta
** Rating: 3.78 / 590
** Description
One of the most important things I’ve learned in the last 7 years has been how to find contentment.  It’s been a long journey, but I’ve enjoyed it. I struggled with feeling bad about my body, feeling insecure about myself, doubting my abilities to make it without an employer, doubting myself as a writer, not believing I had discipline or the ability to change my habits.  And all this led to other problems: I sought happiness and pleasure in food, beer, shopping, distraction,

* The Little Guide to Unprocrastination
** Leo Babauta
** Rating: 3.45 / 187
** Description
Stop putting things off! Start getting things done! Let Leo Babauta show you how in this Little Guide to Unprocrastination. What are you waiting for? Buy the book! Yes, now! Leo Babauta is the author of The Power of Less and the creator and blogger at Zen Habits, a Top 25 blog (according to TIME magazine) with 200,000 subscribers - one of the top productivity and simplicity blogs on the Internet.  The Table of Contents There are 18 brief chapters: My Procrastination Story(Note: the book was first published in 1934, in German, with the title Logik der Forschung. It was "reformulated" into English in 1959. See Wikipedia for details.)

* The Long Goodbye (Philip Marlowe, #6)
** Raymond Chandler
** Rating: 4.22 / 25560
** Description
Marlowe befriends a down on his luck war veteran with the scars to prove it. Then he finds out that Terry Lennox has a very wealthy nymphomaniac wife, who he's divorced and re-married and who ends up dead. And now Lennox is on the lam and the cops and a crazy gangster are after Marlowe.

* The Looming Tower: Al-Qaeda and the Road to 9/11
** Lawrence Wright
** Rating: 4.38 / 15401
** Description

* The Lord of the Rings (The Lord of the Rings, #1-3)
** J.R.R. Tolkien
** Rating: 4.48 / 447386
** Description
A fantastic starter set for new Tolkien fans or readers interested in rediscovering the magic of Middle-earth, this three-volume box set features paperback editions of the complete trilogy -- The Fellowship of the Ring, The Two Towers, and The Return of the King -- each with art from the New Line Productions feature film on the cover. J.R.R. Tolkien's The Lord of the Rings trilogy is a genuine masterpiece. The most widely read and influential fantasy epic of all time, i

* The Man Who Mistook His Wife for a Hat and Other Clinical Tales
** Oliver Sacks
** Rating: 4.04 / 115520
** Description
In his most extraordinary book, "one of the great clinical writers of the twentieth century" (The New York Times) recounts the case histories of patients lost in the bizarre, apparently inescapable world of neurological disorders. Oliver Sacks's The Man Who Mistook His Wife for a Hat tells the stories of individuals afflicted with fantastic perceptual and intellectual aberrations: patients who have lost their memories and with them the greater part of their pasts; who are no longer

* The Metamorphosis
** Franz Kafka
** Rating: 3.79 / 430252
** Description
"As Gregor Samsa awoke one morning from uneasy dreams he found himself transformed in his bed into a gigantic insect. He was laying on his hard, as it were armor-plated, back and when he lifted his head a little he could see his domelike brown belly divided into stiff arched segments on top of which the bed quilt could hardly keep in position and was about to slide off completely. His numerous legs, which were pitifully thin compared to the rest of his bulk, waved helplessly before his eyes." Middle Length Discourses of the Buddha, one of the major collections of texts in the Pali Canon, the authorized scriptures of Theravada Buddhism. This collection--among the oldest records of the historical Buddha's original teachings--consists of 152 suttas or discourses of middle length, distinguished as such from the longer and shorter suttas of the other collections. The Majjhima Nikaya might be concisely

* The Monk and the Riddle: The Education of a Silicon Valley Entrepreneur
** Randy Komisar
** Rating: 3.84 / 1795
** Description
This book describes how one Silicon Valley insider has blazed a path of professional - and personal - success playing the game by his own rules. Silicon Valley is filled with garage-to-riches stories and hot young entrepreneurs with big ideas. Yet even in this place where the exceptional is common, Randy Komisar is a breed apart. Currently a "Virtual CEO" who provides "leadership on demand" for several renowned companies, Komisar was recently described by the "Washington Post" as a "combined pro

* The Mythical Man-Month: Essays on Software Engineering
** Frederick P. Brooks Jr.
** Rating: 4.05 / 8300
** Description
Few books on software project management have been as influential and timeless as The Mythical Man-Month. With a blend of software engineering facts and thought-provoking opinions, Fred Brooks offers insight for anyone managing complex projects. These essays draw from his experience as project manager for the IBM System/360 computer family and then for OS/360, its massive software system. Now, 20 years after the initial publication of his book, Brooks has revisited his original ideas and added n

* The New Business Road Test: What Entrepeneurs and Executives Should Do Before Writing a Business Plan
** John W. Mullins
** Rating: 3.87 / 3760
** Description
More than ever, before you invest your time, talent, or capital in a new business, you'd better make sure the fundamentals are rock-solid. This book shows you how. Leading entrepreneur and consultant John Mullins presents a systematic, up-to-the-minute framework for evaluating any business opportunity, in any industry. Mullins's start-to-finish "seven domains" model brings together scrupulous evaluations of markets, industries, and entrepreneurial teams. Thoroughly updated for today's brutally t

* The Once and Future King (The Once and Future King #1-4)
** T.H. White
** Rating: 4.08 / 84028
** Description
Once upon a time, a young boy called “Wart” was tutored by a magician named Merlyn in preparation for a future he couldn’t possibly imagine. A future in which he would ally himself with the greatest knights, love a legendary queen and unite a country dedicated to chivalrous values. A future that would see him crowned and known for all time as Arthur, King of the Britons.  During Arthur’s reign, the kingdom of Camelot was founded to cast enlightenment on the Dark Ages, while the knights

* The Personal MBA: Master the Art of Business
** Josh Kaufman
** Rating: 4.04 / 14705
** Description
Master the fundamentals, hone your business instincts, and save a fortune in tuition.   The consensus is clear: MBA programs are a waste of time and money. Even the elite schools offer outdated assembly-line educations about profit-and-loss statements and PowerPoint presentations. After two years poring over sanitized case studies, students are shuffled off into middle management to find out how business really works.  Josh Kaufman has made a business out of dis

* The Phantom Tollbooth
** Norton Juster
** Rating: 4.22 / 190152
** Description
Librarian's Note: For an alternate cover edition of the same ISBN, click here.  Hailed as “a classic. . . . humorous, full of warmth and real invention” (The New Yorker), this beloved story -first published more than fifty years ago- introduces readers to Milo and his adventures in the Lands Beyond.   For Milo, everything’s a bore. When a tollbooth mysteriously appears in hi

* The Photographer
** Emmanuel Guibert
** Rating: 4.22 / 2687
** Description
In 1986, Afghanistan was torn apart by a war with the Soviet Union.  This graphic novel/photo-journal is a record of one reporter’s arduous and dangerous journey through Afghanistan, accompanying the Doctors Without Borders.  Didier Lefevre’s photography, paired with the art of Emmanuel Guibert, tells the powerful story of a mission undertaken by men and women dedicated to mending the wounds of war.

* The Poisonwood Bible
** Barbara Kingsolver
** Rating: 4.03 / 569558
** Description
The Poisonwood Bible is a story told by the wife and four daughters of Nathan Price, a fierce, evangelical Baptist who takes his family and mission to the Belgian Congo in 1959. They carry with them everything they believe they will need from home, but soon find that all of it -- from garden seeds to Scripture -- is calamitously transformed on African soil. What follows is a suspenseful epic of one family's tragic undoing and remarkable reconstruction over the course of three decades in postcolo

* The Power Broker: Robert Moses and the Fall of New York
** Robert A. Caro
** Rating: 4.48 / 8138
** Description
One of the most acclaimed books of our time, winner of both the Pulitzer and the Francis Parkman prizes, The Power Broker tells the hidden story behind the shaping (and mis-shaping) of twentieth-century New York (city and state) and makes public what few have known: that Robert Moses was, for almost half a century, the single most powerful man of our time in New York, the shaper not only of the city's politics but of its physical structure and the problems of urban decline that plague us

* The Power Of Less: The Fine Art of Limiting Yourself to the Essential
** Leo Babauta
** Rating: 3.77 / 6090
** Description
With the countless distractions that come from every corner of a modern life, it's amazing that were ever able to accomplish anything. The Power of Less demonstrates how to streamline your life by identifying the essential and eliminating the unnecessary freeing you from everyday clutter and allowing you to focus on accomplishing the goals that can change your life for the better.  The Power of Less will show you how to:    Break any goal down into mana

* The Power of Full Engagement: Managing Energy, Not Time, Is the Key to High Performance and Personal Renewal
** Jim Loehr
** Rating: 4.03 / 9420
** Description
This groundbreaking New York Times bestseller has helped hundreds of thousands of people at work and at home balance stress and recovery and sustain high performance despite crushing workloads and 24/7 demands on their time. “Combines the gritty toughmindedness of the best coaches with the gentle-but-insistent inspiration of the most effective spiritual advisers” (Fast Company).  We live in digital time. Our pace is rushed, rapid-fire, and relentless. Facing crushing work

* The Pragmatic Programmer: From Journeyman to Master
** Andy Hunt
** Rating: 4.31 / 10847
** Description
-- Ward Cunningham Straight from the programming trenches, The Pragmatic Programmer cuts through the increasing specialization and technicalities of modern software development to examine the core process--taking a requirement and producing working, maintainable code that delights its users. It covers topics ranging from personal responsibility and career development to architectural techniques for keeping your code flexible and easy to adapt and reuse. Read this book, and youll learn how to *Fi

* The Prince
** Niccolò Machiavelli
** Rating: 3.78 / 186322
** Description
THE PRINCE was written by Niccolo' Machiavelli in the 1500s. It has continued to be a best seller in many languages. Presently, it is translated into modern English, with illustrations by Benjamin Martinez and an Introduction by Adolph Cso.  The Prince is a classic book that explores the attainment, maintenance, and utilization of political power in the western world. Machiavelli wrote The Prince to demonstrate his skill in the art of the state, presenting advice on how a prince might

* The Princess Bride
** William Goldman
** Rating: 4.25 / 662675
** Description
What happens when the most beautiful girl in the world marries the handsomest prince of all time and he turns out to be...well...a lot less than the man of her dreams?  As a boy, William Goldman claims, he loved to hear his father read the S. Morgenstern classic, The Princess Bride. But as a grown-up he discovered that the boring parts were left out of good old Dad's recitation, and only the "good parts" reached his ears.  Now Goldman does Dad one better. He's reconstructed t

* The Principles of Product Development Flow: Second Generation Lean Product Development
** Donald G. Reinertsen
** Rating: 4.19 / 1322
** Description
In this book, Reinertsen provides an examination of product development practices. He explains why invisible and unmanaged queues are the underlying root cause of poor product development performance. He shows why these queues form and how they undermine the speed, quality, and efficiency in product development.

* The Problems of Philosophy
** Bertrand Russell
** Rating: 3.91 / 9893
** Description
A lively and still one of the best introductions to philosophy, this book pays off both a closer reading for students and specialists, and a casual reading for the general public.

* The Progress Principle: Using Small Wins to Ignite Joy, Engagement, and Creativity at Work
** Teresa Amabile
** Rating: 3.83 / 815
** Description
What really sets the best managers above the rest? It’s their power to build a cadre of employees who have great inner work lives—consistently positive emotions; strong motivation; and favorable perceptions of the organization, their work, and their colleagues. The worst managers undermine inner work life, often unwittingly.  As Teresa Amabile and Steven Kramer explain in The Progress Principle, seemingly mundane workday events can make or break employees’ inner wo

* The Qur'an
** Anonymous
** Rating: 4.34 / 44771
** Description
The Koran is universally accepted by Muslims to be the infallible Word of God as first revealed to the Prophet Muhammad by the Angel Gabriel nearly fourteen hundred years ago. Its 114 chapters, or surahs, recount the narratives central to Muslim belief, and together they form one of the world's most influential prophetic works and a literary masterpiece in its own right. But above all, the Koran provides the rules of conduct that remain fundamental to the Muslim faith today: prayer, fasting, pil

* The Return of the King (The Lord of the Rings, #3)
** J.R.R. Tolkien
** Rating: 4.51 / 521796
** Description
The Companions of the Ring have become involved in separate adventures as the quest continues. Aragorn, revealed as the hidden heir of the ancient Kings of the West, joined with the Riders of Rohan against the forces of Isengard, and took part in the desperate victory of the Hornburg. Merry and Pippin, captured by Orcs, escaped into Fangorn Forest and there encountered the Ents. Gandalf returned, miraculously, and defeated the evil wizard, Saruman. Meanwhile, Sam and Frodo progressed towards Mor

* The Right Stuff
** Tom Wolfe
** Rating: 4.23 / 33588
** Description
Tom Wolfe began The Right Stuff at a time when it was unfashionable to contemplate American heroism. Nixon had left the White House in disgrace, the nation was reeling from the catastrophe of Vietnam, and in 1979--the year the book appeared--Americans were being held hostage by Iranian militants. Yet it was exactly the anachronistic courage of his subjects that captivated Wolfe. In his foreword, he notes that as late as 1970, almost one in four career Navy pilots died in accidents. "Th

* The Rise and Fall of the Third Reich: A History of Nazi Germany
** William L. Shirer
** Rating: 4.15 / 70963
** Description
Hitler boasted that The Third Reich would last a thousand years. It lasted only 12. But those 12 years contained some of the most catastrophic events Western civilization has ever known.No other powerful empire ever bequeathed such mountains of evidence about its birth and destruction as the Third Reich. When the bitter war was over, and before the Nazis could destroy their files, the Allied demand for unconditional surrender produced an almost hour-by-hour record of the nightmare empire buil

* The Road to Serfdom
** Friedrich A. Hayek
** Rating: 4.18 / 14326
** Description
A classic work in political philosophy, intellectual and cultural history, and economics, The Road to Serfdom has inspired and infuriated politicians, scholars, and general readers for half a century. Originally published in England in the spring of 1944—when Eleanor Roosevelt supported the efforts of Stalin, and Albert Einstein subscribed lock, stock, and barrel to the socialist program—The Road to Serfdom was seen as heretical for its passionate warning against the dangers of sta

* The Secret History
** Donna Tartt
** Rating: 4.08 / 196609
** Description
Under the influence of their charismatic classics professor, a group of clever, eccentric misfits at an elite New England college discover a way of thinking and living that is a world away from the humdrum existence of their contemporaries. But when they go beyond the boundaries of normal morality they slip gradually from obsession to corruption and betrayal, and at last - inexorably - into evil.

* The Shining
** Stephen King
** Rating: 4.18 / 846807
** Description
Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to spend reconnecting with his family and working on his writing. But as the harsh winter weather sets in, the idyllic location feels ever more remote...and more sinister. And the only one to notice the strange and terrible forces gathering around the Overlook is Danny Torrance, a uniquely gifted five-year-old.  ©1977

* The Silmarillion
** J.R.R. Tolkien
** Rating: 3.88 / 164490
** Description
The story of the creation of the world and of the First Age, this is the ancient drama to which the characters in The Lord of the Rings look back and in whose events some of them, such as Elrond and Galadriel, took part.   The three Silmarils were jewels created by Fëanor, most gifted of the Elves. Within them was imprisoned the Light of the Two Trees of Valinor before the Trees themselves were destroyed by Morgoth, the first Dark Lord.   Thereafter, the unsullied Light of Va

* The Simple Guide to a Minimalist Life
** Leo Babauta
** Rating: 3.61 / 679
** Description


* The Stand
** Stephen King
** Rating: 4.34 / 482864
** Description
This is the way the world ends: with a nanosecond of computer error in a Defense Department laboratory and a million casual contacts that form the links in a chain letter of death.  And here is the bleak new world of the day after: a world stripped of its institutions and emptied of 99 percent of its people. A world in which a handful of panicky survivors choose sides or are chosen. A world in which good rides on the frail shoulders of the 108-year-old Mother Abigail and the worst nigh

* The Start-Up of You: Adapt to the Future, Invest in Yourself, and Transform Your Career
** Reid Hoffman
** Rating: 3.86 / 5760
** Description
6 hrs and 41 mins  A blueprint for thriving in your job and career in today’s challenging world of work by applying the lessons of Silicon Valley’s most innovative entrepreneurs.   The career escalator is jammed at every level. Unemployment rates are sky-high. Creative disruption is shaking every industry. Global competition for jobs is fierce. The employer-employee pact is over, and traditional job security is a thing of the past.   Here, LinkedIn cofounder and cha

* The Startup Owner's Manual: The Step-By-Step Guide for Building a Great Company
** Steven Gary Blank
** Rating: 4.15 / 5672
** Description
Now a decade after the Four Steps to the Epiphany  sparked the Lean Startup revolution, comes its sequel… The Startup Owner's Manual  The Manual incorporates 10 years of learning and best practices that have swept the startup world. It:  Incorporates the "Business Model Canvas" as the organizing principle for   startup hypotheses Provides separate paths and advice for web/mobile products versus   physical products Offers a wealth of detailed

* The Stranger
** Albert Camus
** Rating: 3.96 / 499006
** Description
This is an alternate cover edition for ISBN 0679720200.  Through the story of an ordinary man unwittingly drawn into a senseless murder on an Algerian beach, Camus explored what he termed "the nakedness of man faced with the absurd." First published in English in 1946; now in a new translation by Matthew Ward.

* The Sun Also Rises
** Ernest Hemingway
** Rating: 3.83 / 308830
** Description
The quintessential novel of the Lost Generation, The Sun Also Rises is one of Ernest Hemingway's masterpieces and a classic example of his spare but powerful writing style. A poignant look at the disillusionment and angst of the post-World War I generation, the novel introduces two of Hemingway's most unforgettable characters: Jake Barnes and Lady Brett Ashley. The story follows the flamboyant Brett and the hapless Jake as they journey from the wild nightlife of 1920s Paris to the brutal

* The Swerve: How the World Became Modern
** Stephen Greenblatt
** Rating: 3.83 / 21314
** Description
One of the world's most celebrated scholars, Stephen Greenblatt has crafted both an innovative work of history and a thrilling story of discovery, in which one manuscript, plucked from a thousand years of neglect, changed the course of human thought and made possible the world as we know it.   Nearly six hundred years ago, a short, genial, cannily alert man in his late thirties took a very old manuscript off a library shelf, saw with excitement what he had discovered, and ordered

* The Things They Carried
** Tim O'Brien
** Rating: 4.12 / 189294
** Description
They carried malaria tablets, love letters, 28-pound mine detectors, dope, illustrated bibles, each other. And if they made it home alive, they carried unrelenting images of a nightmarish war that history is only beginning to absorb. Since its first publication, The Things They Carried has become an unparalleled Vietnam testament, a classic work of American literature, and a profound study of men at war that illuminates the capacity, and the limits, of the human heart and soul. The Unbearable Lightness of Being, Milan Kundera tells the story of a young woman in love with a man torn between his love for her and his incorrigible womanizing and one of his mistresses and her humbly faithful lover. This magnificent novel juxtaposes geographically distant places, brilliant and playful reflections, and a variety of styles to take its place as perhaps the major achievement of one of the world’s truly great writers.

* The Undercover Economist
** Tim Harford
** Rating: 3.79 / 20702
** Description
An economist's version of The Way Things Work, this engaging volume is part field guide to economics and part expose of the economic principles lurking behind daily events, explaining everything from traffic jams to high coffee prices. The Undercover Economist is for anyone who's wondered why the gap between rich and poor nations is so great, or why they can't seem to find a decent second-hand car, or how to outwit Starbucks. This book offers the hidden story behind these and other questions, as

* The Upside of Irrationality: The Unexpected Benefits of Defying Logic at Work and at Home
** Dan Ariely
** Rating: 4.00 / 25094
** Description
The provocative follow-up to the New York Times bestseller Predictably Irrational   Why can large bonuses make CEOs less productive? How can confusing directions actually help us? Why is revenge so important to us? Why is there such a big difference between what we think will make us happy and what really makes us happy?   In his groundbreaking book Predictably Irrational, social scientist Dan Ariely revealed the multiple bias

* The Very Hungry Caterpillar
** Eric Carle
** Rating: 4.29 / 313116
** Description
Eric Carle's The Very Hungry Caterpillar is a perennial favorite with children and adults alike. Its imaginative illustration and clever cut-out detail charts the progress of a very hungry caterpillar as he eats his way through the week.

* The Waste Land
** T.S. Eliot
** Rating: 4.12 / 35249
** Description
The text of Eliot's 1922 masterpiece is accompanied by thorough explanatory annotations as well as by Eliot's own knotty notes, some of which require annotation themselves.  For ease of reading, this Norton Critical Edition presents The Waste Land as it first appeared in the American edition (Boni &amp; Liveright), with Eliot's notes at the end. "Contexts" provides readers with invaluable materials on The Waste Land's sources, composition, and publication history. "Criticism" traces th

* The Waves
** Virginia Woolf
** Rating: 4.14 / 19570
** Description
The Waves is often regarded as Virginia Woolf's masterpiece, standing with those few works of twentieth-century literature that have created unique forms of their own. In deeply poetic prose, Woolf traces the lives of six children from infancy to death who fleetingly unite around the unseen figure of a seventh child, Percival. Allusive and mysterious, The Waves yields new treasures upon each reading.

* The Way We're Working Isn't Working: The Four Forgotten Needs That Energize Great Performance
** Tony Schwartz
** Rating: 3.98 / 1641
** Description

* The Wind in the Willows
** Kenneth Grahame
** Rating: 3.98 / 143751
** Description
One of the most celebrated works of classic literature for children  Meet little Mole, willful Ratty, Badger the perennial bachelor, and petulant Toad. Over one hundred years since their first appearance in 1908, they've become emblematic archetypes of eccentricity, folly, and friendship. And their misadventures-in gypsy caravans, stolen sports cars, and their Wild Wood-continue to capture readers' imaginations and warm their hearts long after they grow up. Begun as a series of

* The Wind-Up Bird Chronicle
** Haruki Murakami
** Rating: 4.17 / 164078
** Description
Japan's most highly regarded novelist now vaults into the first ranks of international fiction writers with this heroically imaginative novel, which is at once a detective story, an account of a disintegrating marriage, and an excavation of the buried secrets of World War II.  In a Tokyo suburb a young man named Toru Okada searches for his wife's missing cat. Soon he finds himself looking for his wife as well in a netherworld that lies beneath the placid surface of Tokyo. As these sear

* The Wisdom of Crowds
** James Surowiecki
** Rating: 3.80 / 19782
** Description
In this fascinating book, New Yorker business columnist James Surowiecki explores a deceptively simple idea: Large groups of people are smarter than an elite few, no matter how brilliant–better at solving problems, fostering innovation, coming to wise decisions, even predicting the future.   With boundless erudition and in delightfully clear prose, Surowiecki ranges across fields as diverse as popular culture, psychology, ant biology, behavioral economics, artificial inte

* The World According to Garp
** John Irving
** Rating: 4.07 / 181246
** Description
This is the life and times of T. S. Garp, the bastard son of Jenny Fields--a feminist leader ahead of her times. This is the life and death of a famous mother and her almost-famous son; theirs is a world of sexual extremes--even of sexual assassinations. It is a novel rich with "lunacy and sorrow"; yet the dark, violent events of the story do not undermine a comedy both ribald and robust. In more than thirty languages, in more than forty countries--with more than ten million copies in print--thi

* The World According to Garp
** John Irving
** Rating: 4.07 / 181246
** Description
This is the life and times of T. S. Garp, the bastard son of Jenny Fields--a feminist leader ahead of her times. This is the life and death of a famous mother and her almost-famous son; theirs is a world of sexual extremes--even of sexual assassinations. It is a novel rich with "lunacy and sorrow"; yet the dark, violent events of the story do not undermine a comedy both ribald and robust. In more than thirty languages, in more than forty countries--with more than ten million copies in print--thi

* The World Is Flat: A Brief History of the Twenty-first Century
** Thomas L. Friedman
** Rating: 3.66 / 85459
** Description
A timely and essential update on globalization, its successes and discontents, powerfully illuminated by one of our most respected journalists.  When scholars write the history of the world twenty years from now, and they come to the chapter "Y2K to March 2004," what will they say was the most crucial development? The attacks on the World Trade Center on 9/11 and the Iraq war? Or the convergence of technology and events that allowed India, China, and so many other countries to become p

* The World Until Yesterday: What Can We Learn from Traditional Societies?
** Jared Diamond
** Rating: 3.69 / 6798
** Description
The bestselling author of Collapse and Guns, Germs and Steel surveys the history of human societies to answer the question: What can we learn from traditional societies that can make the world a better place for all of us? Most of us take for granted the features of our modern society, from air travel and telecommunications to literacy and obesity. Yet for nearly all of its six million years of existence, human society had none of these things. While the gulf that divides

* The Yiddish Policemen's Union
** Michael Chabon
** Rating: 3.70 / 53214
** Description
For sixty years, Jews have prospered in the Federal District of Sitka, a "temporary" safe haven created in the wake of revelations of the Holocaust and the shocking 1948 collapse of the fledgling state of Israel. Now the District is set to revert to Alaskan control, and their dream is coming to an end: once again the tides of history threaten to sweep them up and carry them off into the unknown.  For sixty years, Jewish refugees and their descendants have prospered in the Federal Distr

* Their Eyes Were Watching God
** Zora Neale Hurston
** Rating: 3.87 / 202231
** Description
When Janie, at sixteen, is caught kissing shiftless Johnny Taylor, her grandmother swiftly marries her off to an old man with sixty acres. Janie endures two stifling marriages before meeting the man of her dreams, who offers not diamonds, but a packet of flowering seeds ...  'For me, THEIR EYES WERE WATCHING GOD is one of the very greatest American novels of the 20th century. It is so lyrical it should be sentimental; it is so passionate it should be overwrought, but it is instead a ri

* Things Fall Apart (The African Trilogy, #1)
** Chinua Achebe
** Rating: 3.61 / 218454
** Description
THINGS FALL APART tells two overlapping, intertwining stories, both of which center around Okonkwo, a “strong man” of an Ibo village in Nigeria. The first of these stories traces Okonkwo's fall from grace with the tribal world in which he lives, and in its classical purity of line and economical beauty it provides us with a powerful fable about the immemorial conflict between the individual and society.   The second story, which is as modern as the first is ancient, and which elevates

* Think and Grow Rich: The Landmark Bestseller Now Revised and Updated for the 21st Century
** Napoleon Hill
** Rating: 4.17 / 122494
** Description
Think and Grow Rich has been called the "Granddaddy of All Motivational Literature." It was the first book to boldly ask, "What makes a winner?" The man who asked and listened for the answer, Napoleon Hill, is now counted in the top ranks of the world's winners himself. The most famous of all teachers of success spent "a fortune and the better part of a lifetime of effort" to produce the "Law of Success" philosophy that forms the basis of his books and that is so powerfully summarized in

* Thinkertoys: A Handbook of Creative-Thinking Techniques
** Michael Michalko
** Rating: 4.00 / 2766
** Description
Rethink the Way You Think   In hindsight, every great idea seems obvious. But how can you be the person who comes up with those ideas?  In this revised and expanded edition of his groundbreaking Thinkertoys, creativity expert Michael Michalko reveals life-changing tools that will help you think like a genius. From the linear to the intuitive, this comprehensive handbook details ingenious creative-thinking techniques for approaching problems in unconventional ways. Th

* This Will Make You Smarter: New Scientific Concepts to Improve Your Thinking
** John Brockman
** Rating: 3.81 / 5550
** Description
Edge.org presents brilliant, accessible, cutting-edge ideas to improve our decision-making skills and improve our cognitive toolkits, with contributions by Nassim Nicholas Taleb, Richard Dawkins, Brian Eno, Steven Pinker, and more. Featuring a foreword by New York Times columnist David Brooks and edited by John Brockman, This Will Make You Smarter presents some of the best wisdom from today’s leading thinkers—to make better thinkers out of the leaders of tomorrow.

* Three Cups of Tea: One Man's Mission to Promote Peace ... One School at a Time
** Greg Mortenson
** Rating: 3.64 / 291967
** Description
The inspiring account of one man's campaign to build schools in the most dangerous, remote, and anti-American reaches of Asia.  In April 2011, the CBS documentary "60 Minutes" called into question Greg Mortenson's work. The program alleged inaccuracies in Three Cups of Tea and its sequel, Stones into Schools as well as financial improprieties in the operation of Mortenson's Central Asia Institute. Questions were also raised about Mortenson's claim that he got lost near K2 and ended up

* Thriving on Less: Simplifying in a Tough Economy
** Leo Babauta
** Rating: 3.29 / 75
** Description

* Thus Spoke Zarathustra
** Friedrich Nietzsche
** Rating: 4.05 / 81169
** Description
Friedrich Nietzsche's most accessible and influential philosophical work, misquoted, misrepresented, brilliantly original and enormously influential, Thus Spoke Zarathustra is translated from the German by R.J. Hollingdale in Penguin Classics. Nietzsche was one of the most revolutionary and subversive thinkers in Western philosophy, and Thus Spoke Zarathustra remains his most famous and influential work. It describes how the ancient Persian prophet Zarathustra descends from his solitude in the m

* Toyota Production System: Beyond large-scale production
** Taiichi Ohno
** Rating: 4.03 / 912
** Description
In this classic text, Taiichi Ohno--inventor of the Toyota Production System and Lean manufacturing--shares the genius that sets him apart as one of the most disciplined and creative thinkers of our time. Combining his candid insights with a rigorous analysis of Toyota's attempts at Lean production, Ohno's book explains how Lean principles can improve any production endeavor. A historical and philosophical description of just-in-time and Lean manufacturing, this work is a must read for all stude

* Trainspotting
** Irvine Welsh
** Rating: 4.08 / 113126
** Description
The bestselling novel by Irvine Welsh that provided the inspiration for Danny Boyle’s hit film  Choose us. Choose life. Choose mortgage payments; choose washing machines; choose cars; choose sitting oan a couch watching mind-numbing and spirit-crushing game shows, stuffing fuckin junk food intae yir mooth. Choose rotting away, pishing and shiteing yersel in a home, a total fuckin embarrassment tae the selfish, fucked-up brats ye've produced. Choose life.

* Treasure Island
** Robert Louis Stevenson
** Rating: 3.82 / 318866
** Description
The most popular pirate story ever written in English, featuring one of literature’s most beloved “bad guys,” Treasure Island has been happily devoured by several generations of boys—and girls—and grownups. Its unforgettable characters include: young Jim Hawkins, who finds himself owner of a map to Treasure Island, where the fabled pirate booty is buried; honest Captain Smollett, heroic Dr. Livesey, and the good-hearted but obtuse Squire Trelawney, who help Jim on his quest for the treasu

* Tribal Leadership: Leveraging Natural Groups to Build a Thriving Organization
** Dave Logan
** Rating: 4.01 / 5315
** Description
“Tribal Leadership gives amazingly insightful perspective on how people interact and succeed. I learned about myself and learned lessons I will carry with me and reflect on for the rest of my life.” —John W. Fanning, Founding Chairman and CEO napster Inc.  “An unusually nuanced view of high-performance cultures.”  —Inc.  Within each corporation are anywhere from a few to hundreds of separate tribes. In Tribal Leadership, Dave Logan, John K

* Tribes: We Need You to Lead Us
** Seth Godin
** Rating: 3.83 / 26066
** Description
A tribe is any group of people, large or small, who are connected to one another, a leader, and an idea. For millions of years, humans have been seeking out tribes, be they religious, ethnic, economic, political, or even musical (think of the Deadheads). It's our nature.  Now the Internet has eliminated the barriers of geography, cost, and time. All those blogs and social networking sites are helping existing tribes get bigger. But more important, they're enabling countless new tribes

* Tuesdays with Morrie
** Mitch Albom
** Rating: 4.07 / 599627
** Description
Maybe it was a grandparent, or a teacher or a colleague. Someone older, patient and wise, who understood you when you were young and searching, and gave you sound advice to help you make your way through it. For Mitch Albom, that person was Morrie Schwartz, his college professor from nearly twenty years ago.  Maybe, like Mitch, you lost track of this mentor as you made your way, and the insights faded. Wouldn't you like to see that person again, ask the bigger questions that still haun

* Turning Pro: Tap Your Inner Power and Create Your Life's Work
** Steven Pressfield
** Rating: 4.22 / 5138
** Description
Turning pro is free, but it's not easy.  When we turn pro, we give up a life that we may have become extremely comfortable with. We give up a self that we have come to identify with and to call our own.  Turning pro is free, but it demands sacrifice.  The passage from amateur to professional is often achieved via an interior odyssey whose trials are survived only at great cost, emotionally, psychologically and spiritually. We pass through a membrane wh

* Under the Banner of Heaven: A Story of Violent Faith
** Jon Krakauer
** Rating: 3.98 / 126182
** Description
A multilayered, bone-chilling narrative of messianic delusion, savage violence, polygamy, and unyielding faith. This is vintage Krakauer, an utterly compelling work of nonfiction that illuminates an otherwise confounding realm of human behavior.  Jon Krakauer’s literary reputation rests on insightful chronicles of lives conducted at the outer limits. In Under The Banner of Heaven: A Story of Violent Faith, he shifts his focus from extremes of physical adventure to extremes of religious

* Unleashing the Ideavirus: Stop Marketing AT People! Turn Your Ideas into Epidemics by Helping Your Customers Do the Marketing thing for You.
** Seth Godin
** Rating: 3.97 / 3679
** Description
The book that sparked a marketing revolution.  "This is a subversive book. It says that the marketer is not--and ought not to be--at the center of successful marketing. The customer should be. Are you ready for that?" --From the Foreword by Malcolm Gladwell, author of The Tipping Point.  Counter to traditional marketing wisdom, which tries to count, measure, and manipulate the spread of information, Seth Godin argues that the information can spread m

* Valley of the Dolls
** Jacqueline Susann
** Rating: 3.71 / 38315
** Description

* DONE Watchmen
  CLOSED: [2017-11-24 Fri 03:02]
** Alan Moore
** Rating: 4.35 / 419053
** Description
This Hugo Award-winning graphic novel chronicles the fall from grace of a group of super-heroes plagued by all-too-human failings. Along the way, the concept of the super-hero is dissected as the heroes are stalked by an unknown assassin.  One of the most influential graphic novels of all time and a perennial best-seller, Watchmen has been studied on college campuses across the nation and is considered a gateway title, leading readers to other graphic novels such as V for Ven

* Water for Elephants
** Sara Gruen
** Rating: 4.07 / 1125639
** Description
An atmospheric, gritty, and compelling novel of star-crossed lovers, set in the circus world circa 1932 illuminated by a wonderful sense of time and place. Winner of the 2007 BookBrowse Award for Most Popular Book.  An atmospheric, gritty, and compelling novel of star-crossed lovers, set in the circus world circa 1932, by the bestselling author of Riding Lessons.   When Jacob Jankowski, recently orphaned and suddenly adrift, jumps onto a passing train, he enters a world of fr

* What Got You Here Won't Get You There: How Successful People Become Even More Successful
** Marshall Goldsmith
** Rating: 3.94 / 16539
** Description
America's most sought-after executive coach shows how to climb the last few rungs of the ladder The corporate world is filled with executives, men and women who have worked hard for years to reach the upper levels of management. They're intelligent, skilled, and even charismatic. But only a handful of them will ever reach the pinnacle--and as executive coach Marshall Goldsmith shows in this book, subtle nuances make all the difference. These are small "transactional flaws" perfo

* What the Buddha Taught: Revised and Expanded Edition with Texts from Suttas and Dhammapada
** Walpola Rahula
** Rating: 4.19 / 6454
** Description
This indispensable volume is a lucid and faithful account of the Buddha’s teachings. “For years,” says the Journal of the Buddhist Society, “the newcomer to Buddhism has lacked a simple and reliable introduction to the complexities of the subject. Dr. Rahula’s What the Buddha Taught fills the need as only could be done by one having a firm grasp of the vast material to be sifted. It is a model of what a book should be that is addressed first of all to ‘the educated and intelligent

* Where the Red Fern Grows
** Wilson Rawls
** Rating: 4.04 / 284270
** Description
A loving threesome, they ranged the dark hills and river bottoms of Cherokee country. Old Dan had the brawn. Little Ann had the brains, and Billy had the will to make them into the finest hunting team in the valley. Glory and victory were coming to them, but sadness waited too. Where the Red Fern Grows is an exciting tale of love and adventure you'll never forget.

* Where the Sidewalk Ends
** Shel Silverstein
** Rating: 4.29 / 1037210
** Description
Where the Sidewalk Ends turns forty! Celebrate with this anniversary edition that features an eye-catching commemorative red sticker. This classic poetry collection, which is both outrageously funny and profound, has been the most beloved of Shel Silverstein's poetry books for generations.  Where the sidewalk ends, Shel Silverstein's world begins. There you'll meet a boy who turns into a TV set and a girl who eats a whale. The Unicorn and the Bloath live there, and so does Sarah Cynthi

* Where the Wild Things Are
** Maurice Sendak
** Rating: 4.22 / 652539
** Description
One night Max puts on his wolf suit and makes mischief of one kind and another, so his mother calls him 'Wild Thing' and sends him to bed without his supper. That night a forest begins to grow in Max's room and an ocean rushes by with a boat to take Max to the place where the wild things are. Max tames the wild things and crowns himself as their king, and then the wild rumpus begins. But when Max has sent the monsters to bed, and everything is quiet, he starts to feel lonely and realises it is t

* Whistling Vivaldi: And Other Clues to How Stereotypes Affect Us
** Claude M. Steele
** Rating: 3.86 / 2706
** Description
Through dramatic personal stories, Claude Steele shares the experiments and studies that show, again and again, that exposing subjects to stereotypes—merely reminding a group of female math majors about to take a math test, for example, that women are considered naturally inferior to men at math—impairs their performance in the area affected by the stereotype. Steele’s conclusions shed new light on a host of American social phenomena, from the racial and gender gaps in standardized test scores t

* Why America Is Not a New Rome
** Vaclav Smil
** Rating: 3.63 / 63
** Description
America's post--Cold War strategic dominance and its pre-recession affluence inspired pundits to make celebratory comparisons to ancient Rome at its most powerful. Now, with America no longer perceived as invulnerable, engaged in protracted fighting in Iraq and Afghanistan, and suffering the worst economic downturn since the Great Depression, comparisons are to the bloated, decadent, ineffectual later Empire. In "Why America Is Not a New Rome," Vaclav Smil looks at these comparisons in detail, g

* Why Managing Sucks and How to Fix It: A Results-Only Guide to Taking Control of Work, Not People
** Cali Ressler
** Rating: 3.66 / 107
** Description
Change the way you think about work (and life) by focusing on results--and only results  Why Managing Sucks and How to Fix It shows how the Results-Only Work Environment (ROWE) mindset can make you or your organization more entrepreneurial, more connected with the broader trends in your industry, and more willing to take smart risks. It explains how to set clear expectations and focus on the endpoint as opposed to managing the process that gets you there. With eyes set on

* Why We Buy: The Science of Shopping
** Paco Underhill
** Rating: 3.88 / 9746
** Description
Is there a method to our madness when it comes to shopping? Hailed by the San Francisco Chronicle as "a Sherlock Holmes for retailers," author and research company CEO Paco Underhill answers with a definitive "yes" in this witty, eye-opening report on our ever-evolving consumer culture. Why We Buy is based on hard data gleaned from thousands of hours of field research–in shopping malls, department stores, and supermarkets across America. With his team of sleuths tracking our every move, Paco Und

* Willpower: Rediscovering the Greatest Human Strength
** Roy F. Baumeister
** Rating: 3.95 / 14109
** Description
 One of the world's most esteemed and influential psychologists, Roy F. Baumeister, teams with New York Times science writer John Tierney to reveal the secrets of self-control and how to master it. In Willpower, the pioneering researcher Roy F. Baumeister collaborates with renowned New York Times science writer John Tierney to revolutionize our understanding of the most coveted human virtue: self-control.  In what became one of the most cited papers in socia

* Wittgenstein's Poker: The Story of a Ten-Minute Argument Between Two Great Philosophers
** David Edmonds
** Rating: 3.74 / 2345
** Description
On October 25, 1946, in a crowded room in Cambridge, England, the great twentieth-century philosophers Ludwig Wittgenstein and Karl Popper came face to face for the first and only time. The meeting -- which lasted ten minutes -- did not go well. Their loud and aggressive confrontation became the stuff of instant legend, but precisely what happened during that brief confrontation remained for decades the subject of intense disagreement.  An engaging mix of philosophy, history, biography

* Work the System: The Simple Mechanics of Making More and Working Less
** Sam Carpenter
** Rating: 3.90 / 4223
** Description

* World War Z: An Oral History of the Zombie War
** Max Brooks
** Rating: 4.01 / 353521
** Description
An alternate cover for this isbn can be found here.  The Zombie War came unthinkably close to eradicating humanity. Max Brooks, driven by the urgency of preserving the acid-etched first-hand experiences of the survivors from those apocalyptic years, traveled across the United States of America and throughout the world, from decimated cities that once teemed with upwards of thirty million

* Yes!: 50 Scientifically Proven Ways to Be Persuasive
** Noah J. Goldstein
** Rating: 3.99 / 8715
** Description
Small changes can make a big difference in your powers of persuasion.  What one word can you start using today to increase your persuasiveness by more than fifty percent? Which item of stationery can dramatically increase people's responses to your requests? How can you win over your rivals by inconveniencing them? Why does knowing that so many dentists are named Dennis improve your persuasive prowess?  Every day we face the challenge of persuading others to do

* DONE You Can Draw in 30 Days: The Fun, Easy Way to Learn to Draw in One Month or Less
  CLOSED: [2017-11-24 Fri 03:02]
** Mark Kistler
** Rating: 4.22 / 929
** Description
Learn to draw in 30 days with public television’s favorite drawing teacher. Drawing is an acquired skill, not a talent—anyone can learn to draw! All you need is a pencil, a piece of paper, and the willingness to tap into your hidden artistic abilities. You Can Draw in 30 Days will teach you the rest. With Emmy award–winning, longtime PBS host Mark Kistler as your guide, you’ll learn the secrets of sophisticated three-dimensional renderings, and have fun along the way.

* You Can Negotiate Anything: The World's Best Negotiator Tells You How To Get What You Want
** Herb Cohen
** Rating: 3.83 / 1151
** Description
Herb Cohen believes the world is a giant negotiating table and, like it or not, you're a negotiator. Whether you're dealing with your spouse, boss, department store, bank manager, children, solicitor, or best friend - in every encounter with other people, negotiating is always taking place. And how well you handle those encounters determines whether you prosper happily or suffer frustration and loss. With his helpful and sensible approach Cohen shows that negotiating is a process you can underst

* Your Brain at Work: Strategies for Overcoming Distraction, Regaining Focus, and Working Smarter All Day Long
** David Rock
** Rating: 4.10 / 6284
** Description
Meet Emily and Paul: The parents of two young children, Emily is the newly promoted VP of marketing at a large corporation while Paul works from home or from clients' offices as an independent IT consultant. Their lives, like all of ours, are filled with a bewildering blizzard of emails, phone calls, yet more emails, meetings, projects, proposals, and plans. Just staying ahead of the storm has become a seemingly insurmountable task.  In this book, we travel inside Emily and Paul's brai

* Zen Habits - Handbook for Life
** Leo Babauta
** Rating: 3.72 / 442
** Description
The Zen Habits Handbook for Life is a compilation of Leo Babauta's best articles on living from a Zen Habits perspective. What will this book teach you to do? Basically the same things that Zen Habits aims for overall: how to simplify your life, how to live a happier life, how to be more productive with less stress, how to achieve your dreams. The book includes chapters on decluttering, single-tasking, eliminating nonessentials, planning your day, clearing your inbox, getting motivated, cultivat

* Zen to Done
** Leo Babauta
** Rating: 3.76 / 1666
** Description
